	#==================================================================================================
	#
	# This test program was automatically generated by the MicroTESK tool
	# Generation started: Fri Oct 18 10:42:47 AST 2019
	#
	# Ivannikov Institute for System Programming of the Russian Academy of Sciences (ISP RAS)
	# 25 Alexander Solzhenitsyn st., Moscow, 109004, Russia
	#
	# http://www.microtesk.org
	# http://forge.ispras.ru/projects/microtesk
	#
	#==================================================================================================

	#==================================================================================================
	# Prologue (riscv_test.rb:231)

	#====================================== .section .text.init =======================================
	.section .text.init
	.align 6
	.weak stvec_handler
	.weak mtvec_handler
	.globl _start
_start:
	j reset_vector
	.align 2
trap_vector:
	csrr t5, mcause
	li t6, 0x8
	beq t5, t6, write_tohost
	li t6, 0x9
	beq t5, t6, write_tohost
	li t6, 0xb
	beq t5, t6, write_tohost
	la t5, mtvec_handler
	beqz t5, 1f
	jr t5
1:
	csrr t5, mcause
	bgez t5, handle_exception
	j other_exception
handle_exception:
other_exception:
1:
	ori gp, gp, 1337
write_tohost:
	nop
	sw gp, tohost, t5
	nop
	j write_tohost
reset_vector:
	csrr a0, mhartid
1:
	bnez a0, 1b
	la t0, 1f
	csrw mtvec, t0
	csrwi satp, 0x0
	.align 2
1:
	la t0, 1f
	csrw mtvec, t0
	li t0, 0xffffffffffffffff
	csrw pmpaddr0, t0
	li t0, 0x1f
	csrw pmpcfg0, t0
	.align 2
1:
	la t0, 1f
	csrw mtvec, t0
	csrwi medeleg, 0x0
	csrwi mideleg, 0x0
	csrwi mie, 0x0
	.align 2
1:
	li gp, 0x0
	la t0, trap_vector
	csrw mtvec, t0
	li a0, 0x1
	slli a0, a0, 0x1f
	bgez a0, 1f
	fence
	li gp, 0x1
	ecall
1:
	la t0, stvec_handler
	beqz t0, 1f
	csrw stvec, t0
	li t0, 0xb109
	csrw medeleg, t0
	csrr t1, medeleg
	bne t0, t1, other_exception
1:
	csrwi mstatus, 0x0
	la t0, 1f
	csrw mepc, t0
	csrr a0, mhartid
	mret
1:

	#==================================================================================================
	# External Code (riscv_test_macros.rb:297)

test_2:
	la ra, tdat
	li sp, 0xaa00aa00aa00aa
	sd sp, 0(ra)
	ld t5, 0(ra)
	li t4, 0xaa00aa00aa00aa
	li gp, 0x2
	bne t5, t4, fail
test_3:
	la ra, tdat
	li sp, 0xaa00aa00aa00aa00
	sd sp, 8(ra)
	ld t5, 8(ra)
	li t4, 0xaa00aa00aa00aa00
	li gp, 0x3
	bne t5, t4, fail
test_4:
	la ra, tdat
	li sp, 0xaa00aa00aa00aa0
	sd sp, 16(ra)
	ld t5, 16(ra)
	li t4, 0xaa00aa00aa00aa0
	li gp, 0x4
	bne t5, t4, fail
test_5:
	la ra, tdat
	li sp, 0xa00aa00aa00aa00a
	sd sp, 24(ra)
	ld t5, 24(ra)
	li t4, 0xa00aa00aa00aa00a
	li gp, 0x5
	bne t5, t4, fail
test_6:
	la ra, tdat8
	li sp, 0xaa00aa00aa00aa
	sd sp, -24(ra)
	ld t5, -24(ra)
	li t4, 0xaa00aa00aa00aa
	li gp, 0x6
	bne t5, t4, fail
test_7:
	la ra, tdat8
	li sp, 0xaa00aa00aa00aa00
	sd sp, -16(ra)
	ld t5, -16(ra)
	li t4, 0xaa00aa00aa00aa00
	li gp, 0x7
	bne t5, t4, fail
test_8:
	la ra, tdat8
	li sp, 0xaa00aa00aa00aa0
	sd sp, -8(ra)
	ld t5, -8(ra)
	li t4, 0xaa00aa00aa00aa0
	li gp, 0x8
	bne t5, t4, fail
test_9:
	la ra, tdat8
	li sp, 0xa00aa00aa00aa00a
	sd sp, 0(ra)
	ld t5, 0(ra)
	li t4, 0xa00aa00aa00aa00a
	li gp, 0x9
	bne t5, t4, fail
test_10:
	la ra, tdat9
	li sp, 0x1234567812345678
	addi tp, ra, -32
	sd sp, 32(tp)
	ld t0, 0(ra)
	li t4, 0x1234567812345678
	li gp, 0xa
	bne t0, t4, fail
test_11:
	la ra, tdat9
	li sp, 0x5821309858213098
	addi ra, ra, -3
	sd sp, 11(ra)
	la tp, tdat10
	ld t0, 0(tp)
	li t4, 0x5821309858213098
	li gp, 0xb
	bne t0, t4, fail
test_12:
	li gp, 0xc
	li tp, 0x0
1:
	li ra, 0xabbccdd
	la sp, tdat
	sd ra, 0(sp)
	ld t5, 0(sp)
	li t4, 0xabbccdd
	bne t5, t4, fail
	addi tp, tp, 1
	li t0, 0x2
	bne tp, t0, 1b
test_13:
	li gp, 0xd
	li tp, 0x0
1:
	li ra, 0xaabbccd
	la sp, tdat
	nop
	sd ra, 8(sp)
	ld t5, 8(sp)
	li t4, 0xaabbccd
	bne t5, t4, fail
	addi tp, tp, 1
	li t0, 0x2
	bne tp, t0, 1b
test_14:
	li gp, 0xe
	li tp, 0x0
1:
	li ra, 0xdaabbcc
	la sp, tdat
	nop
	nop
	sd ra, 16(sp)
	ld t5, 16(sp)
	li t4, 0xdaabbcc
	bne t5, t4, fail
	addi tp, tp, 1
	li t0, 0x2
	bne tp, t0, 1b
test_15:
	li gp, 0xf
	li tp, 0x0
1:
	li ra, 0xddaabbc
	nop
	la sp, tdat
	sd ra, 24(sp)
	ld t5, 24(sp)
	li t4, 0xddaabbc
	bne t5, t4, fail
	addi tp, tp, 1
	li t0, 0x2
	bne tp, t0, 1b
test_16:
	li gp, 0x10
	li tp, 0x0
1:
	li ra, 0xcddaabb
	nop
	la sp, tdat
	nop
	sd ra, 32(sp)
	ld t5, 32(sp)
	li t4, 0xcddaabb
	bne t5, t4, fail
	addi tp, tp, 1
	li t0, 0x2
	bne tp, t0, 1b
test_17:
	li gp, 0x11
	li tp, 0x0
1:
	li ra, 0xccddaab
	nop
	nop
	la sp, tdat
	sd ra, 40(sp)
	ld t5, 40(sp)
	li t4, 0xccddaab
	bne t5, t4, fail
	addi tp, tp, 1
	li t0, 0x2
	bne tp, t0, 1b
test_18:
	li gp, 0x12
	li tp, 0x0
1:
	la sp, tdat
	li ra, 0x112233
	sd ra, 0(sp)
	ld t5, 0(sp)
	li t4, 0x112233
	bne t5, t4, fail
	addi tp, tp, 1
	li t0, 0x2
	bne tp, t0, 1b
test_19:
	li gp, 0x13
	li tp, 0x0
1:
	la sp, tdat
	li ra, 0x30011223
	nop
	sd ra, 8(sp)
	ld t5, 8(sp)
	li t4, 0x30011223
	bne t5, t4, fail
	addi tp, tp, 1
	li t0, 0x2
	bne tp, t0, 1b
test_20:
	li gp, 0x14
	li tp, 0x0
1:
	la sp, tdat
	li ra, 0x33001122
	nop
	nop
	sd ra, 16(sp)
	ld t5, 16(sp)
	li t4, 0x33001122
	bne t5, t4, fail
	addi tp, tp, 1
	li t0, 0x2
	bne tp, t0, 1b
test_21:
	li gp, 0x15
	li tp, 0x0
1:
	la sp, tdat
	nop
	li ra, 0x23300112
	sd ra, 24(sp)
	ld t5, 24(sp)
	li t4, 0x23300112
	bne t5, t4, fail
	addi tp, tp, 1
	li t0, 0x2
	bne tp, t0, 1b
test_22:
	li gp, 0x16
	li tp, 0x0
1:
	la sp, tdat
	nop
	li ra, 0x22330011
	nop
	sd ra, 32(sp)
	ld t5, 32(sp)
	li t4, 0x22330011
	bne t5, t4, fail
	addi tp, tp, 1
	li t0, 0x2
	bne tp, t0, 1b
test_23:
	li gp, 0x17
	li tp, 0x0
1:
	la sp, tdat
	nop
	nop
	li ra, 0x12233001
	sd ra, 40(sp)
	ld t5, 40(sp)
	li t4, 0x12233001
	bne t5, t4, fail
	addi tp, tp, 1
	li t0, 0x2
	bne tp, t0, 1b

	#==================================================================================================
	# Epilogue (riscv_test_macros.rb:883)

	bne zero, gp, pass
fail:
	fence
1:
	beqz gp, 1b
	sll gp, gp, ra
	or gp, gp, ra
	ecall
pass:
	fence
	li gp, 0x1
	ecall
	unimp

	#==================================================================================================
	# Data

	#============================================= .data ==============================================
	.data

	#========================================== Global Data ===========================================
	.align 4
	.pushsection .tohost,"aw",@progbits
	.align 8; .global tohost; tohost: .dword 0;
	.align 8; .global fromhost; fromhost: .dword 0;
	.popsection;
	.align 4
	.globl begin_signature
begin_signature:

tdat:
tdat1:
	.dword 0xDEADBEEFDEADBEEF
tdat2:
	.dword 0xDEADBEEFDEADBEEF
tdat3:
	.dword 0xDEADBEEFDEADBEEF
tdat4:
	.dword 0xDEADBEEFDEADBEEF
tdat5:
	.dword 0xDEADBEEFDEADBEEF
tdat6:
	.dword 0xDEADBEEFDEADBEEF
tdat7:
	.dword 0xDEADBEEFDEADBEEF
tdat8:
	.dword 0xDEADBEEFDEADBEEF
tdat9:
	.dword 0xDEADBEEFDEADBEEF
tdat10:
	.dword 0xDEADBEEFDEADBEEF

	.align 4
	.globl end_signature
end_signature:
	.align 8; .global begin_regstate; begin_regstate:
	.word 128;
	.align 8; .global end_regstate; end_regstate:
	.word 4;
