	#==================================================================================================
	#
	# This test program was automatically generated by the MicroTESK tool
	# Generation started: Fri Oct 11 19:18:20 AST 2019
	#
	# Ivannikov Institute for System Programming of the Russian Academy of Sciences (ISP RAS)
	# 25 Alexander Solzhenitsyn st., Moscow, 109004, Russia
	#
	# http://www.microtesk.org
	# http://forge.ispras.ru/projects/microtesk
	#
	#==================================================================================================

	#==================================================================================================
	# Prologue (riscv_test.rb:231)

	#====================================== .section .text.init =======================================
	.section .text.init
	.align 6
	.weak stvec_handler
	.weak mtvec_handler
	.globl _start
_start:
	j reset_vector
	.align 2
trap_vector:
	csrr t5, mcause
	li t6, 0x8
	beq t5, t6, write_tohost
	li t6, 0x9
	beq t5, t6, write_tohost
	li t6, 0xb
	beq t5, t6, write_tohost
	la t5, mtvec_handler
	beqz t5, 1f
	jr t5
1:
	csrr t5, mcause
	bgez t5, handle_exception
	j other_exception
handle_exception:
other_exception:
1:
	ori gp, gp, 1337
write_tohost:
	nop
	sw gp, tohost, t5
	nop
	j write_tohost
reset_vector:
	csrr a0, mhartid
1:
	bnez a0, 1b
	la t0, 1f
	csrw mtvec, t0
	csrwi satp, 0x0
	.align 2
1:
	la t0, 1f
	csrw mtvec, t0
	li t0, 0xffffffffffffffff
	csrw pmpaddr0, t0
	li t0, 0x1f
	csrw pmpcfg0, t0
	.align 2
1:
	la t0, 1f
	csrw mtvec, t0
	csrwi medeleg, 0x0
	csrwi mideleg, 0x0
	csrwi mie, 0x0
	.align 2
1:
	li gp, 0x0
	la t0, trap_vector
	csrw mtvec, t0
	li a0, 0x1
	slli a0, a0, 0x1f
	bgez a0, 1f
	fence
	li gp, 0x1
	ecall
1:
	la t0, stvec_handler
	beqz t0, 1f
	csrw stvec, t0
	li t0, 0xb109
	csrw medeleg, t0
	csrr t1, medeleg
	bne t0, t1, other_exception
1:
	csrwi mstatus, 0x0
	la t0, 1f
	csrw mepc, t0
	csrr a0, mhartid
	mret
1:

	#==================================================================================================
	# External Code (instruction_rv32v_gen1.rb:63)

	addi a0, zero, 32
	vsetvli t0, a0, e32, m4

	#==================================================================================================
	# Test Case 0 (instruction_rv32v_gen1.rb:75)

	la t1, data
	vlw.v v0, t1
	addi t1, t1, 4
	vlw.v v1, t1
	addi t1, t1, 4
	vlw.v v2, t1
	addi t1, t1, 4
	vlw.v v3, t1
	addi t1, t1, 4
	vlw.v v4, t1
	addi t1, t1, 4
	vlw.v v5, t1
	addi t1, t1, 4
	vlw.v v6, t1
	addi t1, t1, 4
	vlw.v v7, t1
	addi t1, t1, 4
	vlw.v v8, t1
	addi t1, t1, 4
	vlw.v v9, t1
	addi t1, t1, 4
	vlw.v v10, t1
	addi t1, t1, 4
	vlw.v v11, t1
	addi t1, t1, 4
	vlw.v v12, t1
	addi t1, t1, 4
	vlw.v v13, t1
	addi t1, t1, 4
	vlw.v v14, t1
	addi t1, t1, 4
	vlw.v v15, t1
	addi t1, t1, 4
	vlw.v v16, t1
	addi t1, t1, 4
	vlw.v v17, t1
	addi t1, t1, 4
	vlw.v v18, t1
	addi t1, t1, 4
	vlw.v v19, t1
	addi t1, t1, 4
	vlw.v v20, t1
	addi t1, t1, 4
	vlw.v v21, t1
	addi t1, t1, 4
	vlw.v v22, t1
	addi t1, t1, 4
	vlw.v v23, t1
	addi t1, t1, 4
	vlw.v v24, t1
	addi t1, t1, 4
	vlw.v v25, t1
	addi t1, t1, 4
	vlw.v v26, t1
	addi t1, t1, 4
	vlw.v v27, t1
	addi t1, t1, 4
	vlw.v v28, t1
	addi t1, t1, 4
	vlw.v v29, t1
	addi t1, t1, 4
	vlw.v v30, t1
	addi t1, t1, 4
	vlw.v v31, t1
	addi t1, t1, 4
	vadd.vv v0, v12, v4
	vadd.vv v28, v12, v4
	vmul.vv v24, v16, v12
	vdiv.vv v16, v8, v20
	vadd.vv v24, v24, v0
	vmul.vv v0, v12, v28
	vadd.vv v4, v8, v20
	vmul.vv v4, v4, v20
	vdiv.vv v0, v12, v4
	vsub.vv v24, v8, v20
	la t1, end
	vsw.v v0, t1
	addi t1, t1, 4
	vsw.v v1, t1
	addi t1, t1, 4
	vsw.v v2, t1
	addi t1, t1, 4
	vsw.v v3, t1
	addi t1, t1, 4
	vsw.v v4, t1
	addi t1, t1, 4
	vsw.v v5, t1
	addi t1, t1, 4
	vsw.v v6, t1
	addi t1, t1, 4
	vsw.v v7, t1
	addi t1, t1, 4
	vsw.v v8, t1
	addi t1, t1, 4
	vsw.v v9, t1
	addi t1, t1, 4
	vsw.v v10, t1
	addi t1, t1, 4
	vsw.v v11, t1
	addi t1, t1, 4
	vsw.v v12, t1
	addi t1, t1, 4
	vsw.v v13, t1
	addi t1, t1, 4
	vsw.v v14, t1
	addi t1, t1, 4
	vsw.v v15, t1
	addi t1, t1, 4
	vsw.v v16, t1
	addi t1, t1, 4
	vsw.v v17, t1
	addi t1, t1, 4
	vsw.v v18, t1
	addi t1, t1, 4
	vsw.v v19, t1
	addi t1, t1, 4
	vsw.v v20, t1
	addi t1, t1, 4
	vsw.v v21, t1
	addi t1, t1, 4
	vsw.v v22, t1
	addi t1, t1, 4
	vsw.v v23, t1
	addi t1, t1, 4
	vsw.v v24, t1
	addi t1, t1, 4
	vsw.v v25, t1
	addi t1, t1, 4
	vsw.v v26, t1
	addi t1, t1, 4
	vsw.v v27, t1
	addi t1, t1, 4
	vsw.v v28, t1
	addi t1, t1, 4
	vsw.v v29, t1
	addi t1, t1, 4
	vsw.v v30, t1
	addi t1, t1, 4
	vsw.v v31, t1
	addi t1, t1, 4
	nop

	#==================================================================================================
	# Self-Checks for Test Case 0

	li sp, 0x80022100
	bne sp, t1, fail

	#==================================================================================================
	# Test Case 1 (instruction_rv32v_gen1.rb:101)

	la t1, end
	addi t1, t1, 0
	lw a0, 0(t1)
	lw a1, 4(t1)
	lw a2, 8(t1)
	lw a3, 12(t1)
	lw a4, 16(t1)
	lw a5, 20(t1)
	lw a6, 24(t1)
	lw a7, 28(t1)

	#==================================================================================================
	# Self-Checks for Test Case 1

	li sp, 0x80022080
	bne sp, t1, fail
	li sp, 0xfffffffffffffffe
	bne sp, a0, fail
	ori sp, zero, 1
	bne sp, a1, fail
	ori sp, zero, 3
	bne sp, a2, fail
	ori sp, zero, 1
	bne sp, a3, fail
	li sp, 0xffffffffcca05c61
	bne sp, a4, fail
	li sp, 0x354478bc
	bne sp, a5, fail
	li sp, 0x269420ba
	bne sp, a6, fail
	li sp, 0x3b0667ec
	bne sp, a7, fail

	#==================================================================================================
	# Test Case 2 (instruction_rv32v_gen1.rb:101)

	la t1, end
	addi t1, t1, 32
	lw a0, 0(t1)
	lw a1, 4(t1)
	lw a2, 8(t1)
	lw a3, 12(t1)
	lw a4, 16(t1)
	lw a5, 20(t1)
	lw a6, 24(t1)
	lw a7, 28(t1)

	#==================================================================================================
	# Self-Checks for Test Case 2

	li sp, 0x800220a0
	bne sp, t1, fail
	li sp, 0xffffffffea065b28
	bne sp, a0, fail
	li sp, 0x2850aa8b
	bne sp, a1, fail
	li sp, 0xffffffffa5f25cbd
	bne sp, a2, fail
	li sp, 0x563ebde5
	bne sp, a3, fail
	li sp, 0x6884a2fa
	bne sp, a4, fail
	li sp, 0x523b2453
	bne sp, a5, fail
	li sp, 0x7d9d2f07
	bne sp, a6, fail
	li sp, 0x62210d5a
	bne sp, a7, fail

	#==================================================================================================
	# Test Case 3 (instruction_rv32v_gen1.rb:101)

	la t1, end
	addi t1, t1, 64
	lw a0, 0(t1)
	lw a1, 4(t1)
	lw a2, 8(t1)
	lw a3, 12(t1)
	lw a4, 16(t1)
	lw a5, 20(t1)
	lw a6, 24(t1)
	lw a7, 28(t1)

	#==================================================================================================
	# Self-Checks for Test Case 3

	li sp, 0x800220c0
	bne sp, t1, fail
	bne zero, a0, fail
	ori sp, zero, 5
	bne sp, a1, fail
	ori sp, zero, 1
	bne sp, a2, fail
	li sp, 0xfffffffffffffffd
	bne sp, a3, fail
	li sp, 0xffffffffe15e3c45
	bne sp, a4, fail
	li sp, 0x774c784
	bne sp, a5, fail
	li sp, 0xffffffffa949f2ae
	bne sp, a6, fail
	li sp, 0xffffffffe4e0812c
	bne sp, a7, fail

	#==================================================================================================
	# Test Case 4 (instruction_rv32v_gen1.rb:101)

	la t1, end
	addi t1, t1, 96
	lw a0, 0(t1)
	lw a1, 4(t1)
	lw a2, 8(t1)
	lw a3, 12(t1)
	lw a4, 16(t1)
	lw a5, 20(t1)
	lw a6, 24(t1)
	lw a7, 28(t1)

	#==================================================================================================
	# Self-Checks for Test Case 4

	li sp, 0x800220e0
	bne sp, t1, fail
	li sp, 0x8a81ee3
	bne sp, a0, fail
	li sp, 0x20dbe307
	bne sp, a1, fail
	li sp, 0xfffffffffca86a0f
	bne sp, a2, fail
	li sp, 0x715e3cb9
	bne sp, a3, fail
	li sp, 0x29e33689
	bne sp, a4, fail
	li sp, 0xffffffffa4af1975
	bne sp, a5, fail
	li sp, 0x36fbeab7
	bne sp, a6, fail
	li sp, 0x190a2f19
	bne sp, a7, fail

	#==================================================================================================
	# Test Case 5 (instruction_rv32v_gen1.rb:75)

	la t1, data
	vlw.v v0, t1
	addi t1, t1, 4
	vlw.v v1, t1
	addi t1, t1, 4
	vlw.v v2, t1
	addi t1, t1, 4
	vlw.v v3, t1
	addi t1, t1, 4
	vlw.v v4, t1
	addi t1, t1, 4
	vlw.v v5, t1
	addi t1, t1, 4
	vlw.v v6, t1
	addi t1, t1, 4
	vlw.v v7, t1
	addi t1, t1, 4
	vlw.v v8, t1
	addi t1, t1, 4
	vlw.v v9, t1
	addi t1, t1, 4
	vlw.v v10, t1
	addi t1, t1, 4
	vlw.v v11, t1
	addi t1, t1, 4
	vlw.v v12, t1
	addi t1, t1, 4
	vlw.v v13, t1
	addi t1, t1, 4
	vlw.v v14, t1
	addi t1, t1, 4
	vlw.v v15, t1
	addi t1, t1, 4
	vlw.v v16, t1
	addi t1, t1, 4
	vlw.v v17, t1
	addi t1, t1, 4
	vlw.v v18, t1
	addi t1, t1, 4
	vlw.v v19, t1
	addi t1, t1, 4
	vlw.v v20, t1
	addi t1, t1, 4
	vlw.v v21, t1
	addi t1, t1, 4
	vlw.v v22, t1
	addi t1, t1, 4
	vlw.v v23, t1
	addi t1, t1, 4
	vlw.v v24, t1
	addi t1, t1, 4
	vlw.v v25, t1
	addi t1, t1, 4
	vlw.v v26, t1
	addi t1, t1, 4
	vlw.v v27, t1
	addi t1, t1, 4
	vlw.v v28, t1
	addi t1, t1, 4
	vlw.v v29, t1
	addi t1, t1, 4
	vlw.v v30, t1
	addi t1, t1, 4
	vlw.v v31, t1
	addi t1, t1, 4
	vsub.vv v8, v20, v20
	vadd.vv v24, v12, v8
	vmul.vv v16, v24, v4
	vsub.vv v4, v4, v16
	vdiv.vv v16, v12, v20
	vadd.vv v8, v24, v8
	vsub.vv v16, v0, v8
	vdiv.vv v4, v16, v28
	vadd.vv v8, v0, v4
	vdiv.vv v12, v24, v16
	la t1, end
	vsw.v v0, t1
	addi t1, t1, 4
	vsw.v v1, t1
	addi t1, t1, 4
	vsw.v v2, t1
	addi t1, t1, 4
	vsw.v v3, t1
	addi t1, t1, 4
	vsw.v v4, t1
	addi t1, t1, 4
	vsw.v v5, t1
	addi t1, t1, 4
	vsw.v v6, t1
	addi t1, t1, 4
	vsw.v v7, t1
	addi t1, t1, 4
	vsw.v v8, t1
	addi t1, t1, 4
	vsw.v v9, t1
	addi t1, t1, 4
	vsw.v v10, t1
	addi t1, t1, 4
	vsw.v v11, t1
	addi t1, t1, 4
	vsw.v v12, t1
	addi t1, t1, 4
	vsw.v v13, t1
	addi t1, t1, 4
	vsw.v v14, t1
	addi t1, t1, 4
	vsw.v v15, t1
	addi t1, t1, 4
	vsw.v v16, t1
	addi t1, t1, 4
	vsw.v v17, t1
	addi t1, t1, 4
	vsw.v v18, t1
	addi t1, t1, 4
	vsw.v v19, t1
	addi t1, t1, 4
	vsw.v v20, t1
	addi t1, t1, 4
	vsw.v v21, t1
	addi t1, t1, 4
	vsw.v v22, t1
	addi t1, t1, 4
	vsw.v v23, t1
	addi t1, t1, 4
	vsw.v v24, t1
	addi t1, t1, 4
	vsw.v v25, t1
	addi t1, t1, 4
	vsw.v v26, t1
	addi t1, t1, 4
	vsw.v v27, t1
	addi t1, t1, 4
	vsw.v v28, t1
	addi t1, t1, 4
	vsw.v v29, t1
	addi t1, t1, 4
	vsw.v v30, t1
	addi t1, t1, 4
	vsw.v v31, t1
	addi t1, t1, 4
	nop

	#==================================================================================================
	# Self-Checks for Test Case 5

	li sp, 0x80022100
	bne sp, t1, fail

	#==================================================================================================
	# Test Case 6 (instruction_rv32v_gen1.rb:101)

	la t1, end
	addi t1, t1, 0
	lw a0, 0(t1)
	lw a1, 4(t1)
	lw a2, 8(t1)
	lw a3, 12(t1)
	lw a4, 16(t1)
	lw a5, 20(t1)
	lw a6, 24(t1)
	lw a7, 28(t1)

	#==================================================================================================
	# Self-Checks for Test Case 6

	li sp, 0x80022080
	bne sp, t1, fail
	li sp, 0x58dc02e
	bne sp, a0, fail
	li sp, 0xffffffff99e76af6
	bne sp, a1, fail
	li sp, 0xfffffffff044c4aa
	bne sp, a2, fail
	li sp, 0x46bf6b91
	bne sp, a3, fail
	ori sp, zero, 1
	bne sp, a4, fail
	li sp, 0xfffffffffffffffd
	bne sp, a5, fail
	not sp, zero
	bne sp, a6, fail
	bne zero, a7, fail

	#==================================================================================================
	# Test Case 7 (instruction_rv32v_gen1.rb:101)

	la t1, end
	addi t1, t1, 32
	lw a0, 0(t1)
	lw a1, 4(t1)
	lw a2, 8(t1)
	lw a3, 12(t1)
	lw a4, 16(t1)
	lw a5, 20(t1)
	lw a6, 24(t1)
	lw a7, 28(t1)

	#==================================================================================================
	# Self-Checks for Test Case 7

	li sp, 0x800220a0
	bne sp, t1, fail
	li sp, 0x58dc02f
	bne sp, a0, fail
	li sp, 0xffffffff99e76af3
	bne sp, a1, fail
	li sp, 0xfffffffff044c4a9
	bne sp, a2, fail
	li sp, 0x46bf6b91
	bne sp, a3, fail
	not sp, zero
	bne sp, a4, fail
	ori sp, zero, 1
	bne sp, a5, fail
	ori sp, zero, 1
	bne sp, a6, fail
	li sp, 0xfffffffffffffffd
	bne sp, a7, fail

	#==================================================================================================
	# Test Case 8 (instruction_rv32v_gen1.rb:101)

	la t1, end
	addi t1, t1, 64
	lw a0, 0(t1)
	lw a1, 4(t1)
	lw a2, 8(t1)
	lw a3, 12(t1)
	lw a4, 16(t1)
	lw a5, 20(t1)
	lw a6, 24(t1)
	lw a7, 28(t1)

	#==================================================================================================
	# Self-Checks for Test Case 8

	li sp, 0x800220c0
	bne sp, t1, fail
	li sp, 0xffffffff9d091d34
	bne sp, a0, fail
	li sp, 0x47ac46a3
	bne sp, a1, fail
	li sp, 0x72a795a3
	bne sp, a2, fail
	li sp, 0xffffffffe49e5e37
	bne sp, a3, fail
	li sp, 0xffffffffe15e3c45
	bne sp, a4, fail
	li sp, 0x774c784
	bne sp, a5, fail
	li sp, 0xffffffffa949f2ae
	bne sp, a6, fail
	li sp, 0xffffffffe4e0812c
	bne sp, a7, fail

	#==================================================================================================
	# Test Case 9 (instruction_rv32v_gen1.rb:101)

	la t1, end
	addi t1, t1, 96
	lw a0, 0(t1)
	lw a1, 4(t1)
	lw a2, 8(t1)
	lw a3, 12(t1)
	lw a4, 16(t1)
	lw a5, 20(t1)
	lw a6, 24(t1)
	lw a7, 28(t1)

	#==================================================================================================
	# Self-Checks for Test Case 9

	li sp, 0x800220e0
	bne sp, t1, fail
	li sp, 0x6884a2fa
	bne sp, a0, fail
	li sp, 0x523b2453
	bne sp, a1, fail
	li sp, 0x7d9d2f07
	bne sp, a2, fail
	li sp, 0x62210d5a
	bne sp, a3, fail
	li sp, 0xffffffffb20b10c6
	bne sp, a4, fail
	li sp, 0xffffffffe90dc1a8
	bne sp, a5, fail
	li sp, 0xffffffffaeccc83a
	bne sp, a6, fail
	li sp, 0x6182909b
	bne sp, a7, fail

	#==================================================================================================
	# Test Case 10 (instruction_rv32v_gen1.rb:75)

	la t1, data
	vlw.v v0, t1
	addi t1, t1, 4
	vlw.v v1, t1
	addi t1, t1, 4
	vlw.v v2, t1
	addi t1, t1, 4
	vlw.v v3, t1
	addi t1, t1, 4
	vlw.v v4, t1
	addi t1, t1, 4
	vlw.v v5, t1
	addi t1, t1, 4
	vlw.v v6, t1
	addi t1, t1, 4
	vlw.v v7, t1
	addi t1, t1, 4
	vlw.v v8, t1
	addi t1, t1, 4
	vlw.v v9, t1
	addi t1, t1, 4
	vlw.v v10, t1
	addi t1, t1, 4
	vlw.v v11, t1
	addi t1, t1, 4
	vlw.v v12, t1
	addi t1, t1, 4
	vlw.v v13, t1
	addi t1, t1, 4
	vlw.v v14, t1
	addi t1, t1, 4
	vlw.v v15, t1
	addi t1, t1, 4
	vlw.v v16, t1
	addi t1, t1, 4
	vlw.v v17, t1
	addi t1, t1, 4
	vlw.v v18, t1
	addi t1, t1, 4
	vlw.v v19, t1
	addi t1, t1, 4
	vlw.v v20, t1
	addi t1, t1, 4
	vlw.v v21, t1
	addi t1, t1, 4
	vlw.v v22, t1
	addi t1, t1, 4
	vlw.v v23, t1
	addi t1, t1, 4
	vlw.v v24, t1
	addi t1, t1, 4
	vlw.v v25, t1
	addi t1, t1, 4
	vlw.v v26, t1
	addi t1, t1, 4
	vlw.v v27, t1
	addi t1, t1, 4
	vlw.v v28, t1
	addi t1, t1, 4
	vlw.v v29, t1
	addi t1, t1, 4
	vlw.v v30, t1
	addi t1, t1, 4
	vlw.v v31, t1
	addi t1, t1, 4
	vadd.vv v8, v4, v0
	vmul.vv v12, v8, v0
	vadd.vv v12, v4, v16
	vdiv.vv v0, v28, v0
	vadd.vv v16, v20, v8
	vmul.vv v20, v24, v8
	vsub.vv v12, v16, v8
	vadd.vv v8, v20, v4
	vsub.vv v20, v24, v24
	vmul.vv v16, v0, v24
	la t1, end
	vsw.v v0, t1
	addi t1, t1, 4
	vsw.v v1, t1
	addi t1, t1, 4
	vsw.v v2, t1
	addi t1, t1, 4
	vsw.v v3, t1
	addi t1, t1, 4
	vsw.v v4, t1
	addi t1, t1, 4
	vsw.v v5, t1
	addi t1, t1, 4
	vsw.v v6, t1
	addi t1, t1, 4
	vsw.v v7, t1
	addi t1, t1, 4
	vsw.v v8, t1
	addi t1, t1, 4
	vsw.v v9, t1
	addi t1, t1, 4
	vsw.v v10, t1
	addi t1, t1, 4
	vsw.v v11, t1
	addi t1, t1, 4
	vsw.v v12, t1
	addi t1, t1, 4
	vsw.v v13, t1
	addi t1, t1, 4
	vsw.v v14, t1
	addi t1, t1, 4
	vsw.v v15, t1
	addi t1, t1, 4
	vsw.v v16, t1
	addi t1, t1, 4
	vsw.v v17, t1
	addi t1, t1, 4
	vsw.v v18, t1
	addi t1, t1, 4
	vsw.v v19, t1
	addi t1, t1, 4
	vsw.v v20, t1
	addi t1, t1, 4
	vsw.v v21, t1
	addi t1, t1, 4
	vsw.v v22, t1
	addi t1, t1, 4
	vsw.v v23, t1
	addi t1, t1, 4
	vsw.v v24, t1
	addi t1, t1, 4
	vsw.v v25, t1
	addi t1, t1, 4
	vsw.v v26, t1
	addi t1, t1, 4
	vsw.v v27, t1
	addi t1, t1, 4
	vsw.v v28, t1
	addi t1, t1, 4
	vsw.v v29, t1
	addi t1, t1, 4
	vsw.v v30, t1
	addi t1, t1, 4
	vsw.v v31, t1
	addi t1, t1, 4
	nop

	#==================================================================================================
	# Self-Checks for Test Case 10

	li sp, 0x80022100
	bne sp, t1, fail

	#==================================================================================================
	# Test Case 11 (instruction_rv32v_gen1.rb:101)

	la t1, end
	addi t1, t1, 0
	lw a0, 0(t1)
	lw a1, 4(t1)
	lw a2, 8(t1)
	lw a3, 12(t1)
	lw a4, 16(t1)
	lw a5, 20(t1)
	lw a6, 24(t1)
	lw a7, 28(t1)

	#==================================================================================================
	# Self-Checks for Test Case 11

	li sp, 0x80022080
	bne sp, t1, fail
	li sp, 0xfffffffffffffff2
	bne sp, a0, fail
	bne zero, a1, fail
	ori sp, zero, 5
	bne sp, a2, fail
	ori sp, zero, 1
	bne sp, a3, fail
	li sp, 0xffffffffc15e938f
	bne sp, a4, fail
	li sp, 0x5273f522
	bne sp, a5, fail
	li sp, 0xffffffffb95ebbb0
	bne sp, a6, fail
	li sp, 0xffffffffb6e921bf
	bne sp, a7, fail

	#==================================================================================================
	# Test Case 12 (instruction_rv32v_gen1.rb:101)

	la t1, end
	addi t1, t1, 32
	lw a0, 0(t1)
	lw a1, 4(t1)
	lw a2, 8(t1)
	lw a3, 12(t1)
	lw a4, 16(t1)
	lw a5, 20(t1)
	lw a6, 24(t1)
	lw a7, 28(t1)

	#==================================================================================================
	# Self-Checks for Test Case 12

	li sp, 0x800220a0
	bne sp, t1, fail
	li sp, 0xffffffffbdc72baa
	bne sp, a0, fail
	li sp, 0x4f53522
	bne sp, a1, fail
	li sp, 0x581c8248
	bne sp, a2, fail
	li sp, 0x17e44eef
	bne sp, a3, fail
	li sp, 0xffffffffe15e3c45
	bne sp, a4, fail
	li sp, 0x774c784
	bne sp, a5, fail
	li sp, 0xffffffffa949f2ae
	bne sp, a6, fail
	li sp, 0xffffffffe4e0812c
	bne sp, a7, fail

	#==================================================================================================
	# Test Case 13 (instruction_rv32v_gen1.rb:101)

	la t1, end
	addi t1, t1, 64
	lw a0, 0(t1)
	lw a1, 4(t1)
	lw a2, 8(t1)
	lw a3, 12(t1)
	lw a4, 16(t1)
	lw a5, 20(t1)
	lw a6, 24(t1)
	lw a7, 28(t1)

	#==================================================================================================
	# Self-Checks for Test Case 13

	li sp, 0x800220c0
	bne sp, t1, fail
	li sp, 0xffffffff947c0dfe
	bne sp, a0, fail
	bne zero, a1, fail
	li sp, 0xffffffffd467c3ec
	bne sp, a2, fail
	li sp, 0xffffffffbee8a107
	bne sp, a3, fail
	bne zero, a4, fail
	bne zero, a5, fail
	bne zero, a6, fail
	bne zero, a7, fail

	#==================================================================================================
	# Test Case 14 (instruction_rv32v_gen1.rb:101)

	la t1, end
	addi t1, t1, 96
	lw a0, 0(t1)
	lw a1, 4(t1)
	lw a2, 8(t1)
	lw a3, 12(t1)
	lw a4, 16(t1)
	lw a5, 20(t1)
	lw a6, 24(t1)
	lw a7, 28(t1)

	#==================================================================================================
	# Self-Checks for Test Case 14

	li sp, 0x800220e0
	bne sp, t1, fail
	li sp, 0xffffffffbe896cb7
	bne sp, a0, fail
	li sp, 0x583ab800
	bne sp, a1, fail
	li sp, 0xfffffffff747f3fc
	bne sp, a2, fail
	li sp, 0xffffffffbee8a107
	bne sp, a3, fail
	li sp, 0xffffffffb20b10c6
	bne sp, a4, fail
	li sp, 0xffffffffe90dc1a8
	bne sp, a5, fail
	li sp, 0xffffffffaeccc83a
	bne sp, a6, fail
	li sp, 0x6182909b
	bne sp, a7, fail

	#==================================================================================================
	# Test Case 15 (instruction_rv32v_gen1.rb:75)

	la t1, data
	vlw.v v0, t1
	addi t1, t1, 4
	vlw.v v1, t1
	addi t1, t1, 4
	vlw.v v2, t1
	addi t1, t1, 4
	vlw.v v3, t1
	addi t1, t1, 4
	vlw.v v4, t1
	addi t1, t1, 4
	vlw.v v5, t1
	addi t1, t1, 4
	vlw.v v6, t1
	addi t1, t1, 4
	vlw.v v7, t1
	addi t1, t1, 4
	vlw.v v8, t1
	addi t1, t1, 4
	vlw.v v9, t1
	addi t1, t1, 4
	vlw.v v10, t1
	addi t1, t1, 4
	vlw.v v11, t1
	addi t1, t1, 4
	vlw.v v12, t1
	addi t1, t1, 4
	vlw.v v13, t1
	addi t1, t1, 4
	vlw.v v14, t1
	addi t1, t1, 4
	vlw.v v15, t1
	addi t1, t1, 4
	vlw.v v16, t1
	addi t1, t1, 4
	vlw.v v17, t1
	addi t1, t1, 4
	vlw.v v18, t1
	addi t1, t1, 4
	vlw.v v19, t1
	addi t1, t1, 4
	vlw.v v20, t1
	addi t1, t1, 4
	vlw.v v21, t1
	addi t1, t1, 4
	vlw.v v22, t1
	addi t1, t1, 4
	vlw.v v23, t1
	addi t1, t1, 4
	vlw.v v24, t1
	addi t1, t1, 4
	vlw.v v25, t1
	addi t1, t1, 4
	vlw.v v26, t1
	addi t1, t1, 4
	vlw.v v27, t1
	addi t1, t1, 4
	vlw.v v28, t1
	addi t1, t1, 4
	vlw.v v29, t1
	addi t1, t1, 4
	vlw.v v30, t1
	addi t1, t1, 4
	vlw.v v31, t1
	addi t1, t1, 4
	vdiv.vv v20, v24, v8
	vmul.vv v4, v16, v8
	vadd.vv v28, v4, v0
	vmul.vv v8, v4, v24
	vdiv.vv v8, v12, v8
	vadd.vv v24, v0, v20
	vsub.vv v0, v24, v0
	vadd.vv v0, v20, v16
	vdiv.vv v28, v0, v8
	vadd.vv v0, v0, v24
	la t1, end
	vsw.v v0, t1
	addi t1, t1, 4
	vsw.v v1, t1
	addi t1, t1, 4
	vsw.v v2, t1
	addi t1, t1, 4
	vsw.v v3, t1
	addi t1, t1, 4
	vsw.v v4, t1
	addi t1, t1, 4
	vsw.v v5, t1
	addi t1, t1, 4
	vsw.v v6, t1
	addi t1, t1, 4
	vsw.v v7, t1
	addi t1, t1, 4
	vsw.v v8, t1
	addi t1, t1, 4
	vsw.v v9, t1
	addi t1, t1, 4
	vsw.v v10, t1
	addi t1, t1, 4
	vsw.v v11, t1
	addi t1, t1, 4
	vsw.v v12, t1
	addi t1, t1, 4
	vsw.v v13, t1
	addi t1, t1, 4
	vsw.v v14, t1
	addi t1, t1, 4
	vsw.v v15, t1
	addi t1, t1, 4
	vsw.v v16, t1
	addi t1, t1, 4
	vsw.v v17, t1
	addi t1, t1, 4
	vsw.v v18, t1
	addi t1, t1, 4
	vsw.v v19, t1
	addi t1, t1, 4
	vsw.v v20, t1
	addi t1, t1, 4
	vsw.v v21, t1
	addi t1, t1, 4
	vsw.v v22, t1
	addi t1, t1, 4
	vsw.v v23, t1
	addi t1, t1, 4
	vsw.v v24, t1
	addi t1, t1, 4
	vsw.v v25, t1
	addi t1, t1, 4
	vsw.v v26, t1
	addi t1, t1, 4
	vsw.v v27, t1
	addi t1, t1, 4
	vsw.v v28, t1
	addi t1, t1, 4
	vsw.v v29, t1
	addi t1, t1, 4
	vsw.v v30, t1
	addi t1, t1, 4
	vsw.v v31, t1
	addi t1, t1, 4
	nop

	#==================================================================================================
	# Self-Checks for Test Case 15

	li sp, 0x80022100
	bne sp, t1, fail

	#==================================================================================================
	# Test Case 16 (instruction_rv32v_gen1.rb:101)

	la t1, end
	addi t1, t1, 0
	lw a0, 0(t1)
	lw a1, 4(t1)
	lw a2, 8(t1)
	lw a3, 12(t1)
	lw a4, 16(t1)
	lw a5, 20(t1)
	lw a6, 24(t1)
	lw a7, 28(t1)

	#==================================================================================================
	# Self-Checks for Test Case 16

	li sp, 0x80022080
	bne sp, t1, fail
	li sp, 0x133a3ea2
	bne sp, a0, fail
	li sp, 0xffffffff8c8334a3
	bne sp, a1, fail
	li sp, 0x2e42a622
	bne sp, a2, fail
	li sp, 0x62e20977
	bne sp, a3, fail
	li sp, 0xffffffffca859180
	bne sp, a4, fail
	li sp, 0xffffffff9b50b8c3
	bne sp, a5, fail
	li sp, 0x7ce69598
	bne sp, a6, fail
	li sp, 0x3b3e0cbe
	bne sp, a7, fail

	#==================================================================================================
	# Test Case 17 (instruction_rv32v_gen1.rb:101)

	la t1, end
	addi t1, t1, 32
	lw a0, 0(t1)
	lw a1, 4(t1)
	lw a2, 8(t1)
	lw a3, 12(t1)
	lw a4, 16(t1)
	lw a5, 20(t1)
	lw a6, 24(t1)
	lw a7, 28(t1)

	#==================================================================================================
	# Self-Checks for Test Case 17

	li sp, 0x800220a0
	bne sp, t1, fail
	li sp, 0xffffffffffffffe4
	bne sp, a0, fail
	li sp, 0xfffffffffffffffd
	bne sp, a1, fail
	li sp, 0xfffffffffffffff1
	bne sp, a2, fail
	ori sp, zero, 1
	bne sp, a3, fail
	li sp, 0x6884a2fa
	bne sp, a4, fail
	li sp, 0x523b2453
	bne sp, a5, fail
	li sp, 0x7d9d2f07
	bne sp, a6, fail
	li sp, 0x62210d5a
	bne sp, a7, fail

	#==================================================================================================
	# Test Case 18 (instruction_rv32v_gen1.rb:101)

	la t1, end
	addi t1, t1, 64
	lw a0, 0(t1)
	lw a1, 4(t1)
	lw a2, 8(t1)
	lw a3, 12(t1)
	lw a4, 16(t1)
	lw a5, 20(t1)
	lw a6, 24(t1)
	lw a7, 28(t1)

	#==================================================================================================
	# Self-Checks for Test Case 18

	li sp, 0x800220c0
	bne sp, t1, fail
	li sp, 0xdac7e70
	bne sp, a0, fail
	li sp, 0xfffffffff29bc9a9
	bne sp, a1, fail
	li sp, 0x3dfde178
	bne sp, a2, fail
	li sp, 0x1c229de6
	bne sp, a3, fail
	ori sp, zero, 2
	bne sp, a4, fail
	ori sp, zero, 2
	bne sp, a5, fail
	bne zero, a6, fail
	bne zero, a7, fail

	#==================================================================================================
	# Test Case 19 (instruction_rv32v_gen1.rb:101)

	la t1, end
	addi t1, t1, 96
	lw a0, 0(t1)
	lw a1, 4(t1)
	lw a2, 8(t1)
	lw a3, 12(t1)
	lw a4, 16(t1)
	lw a5, 20(t1)
	lw a6, 24(t1)
	lw a7, 28(t1)

	#==================================================================================================
	# Self-Checks for Test Case 19

	li sp, 0x800220e0
	bne sp, t1, fail
	li sp, 0x58dc030
	bne sp, a0, fail
	li sp, 0xffffffff99e76af8
	bne sp, a1, fail
	li sp, 0xfffffffff044c4aa
	bne sp, a2, fail
	li sp, 0x46bf6b91
	bne sp, a3, fail
	li sp, 0xffffffffff82fb7c
	bne sp, a4, fail
	li sp, 0x476bcc7
	bne sp, a5, fail
	li sp, 0xfffffffffbde020a
	bne sp, a6, fail
	li sp, 0x1c229de6
	bne sp, a7, fail

	#==================================================================================================
	# Test Case 20 (instruction_rv32v_gen1.rb:75)

	la t1, data
	vlw.v v0, t1
	addi t1, t1, 4
	vlw.v v1, t1
	addi t1, t1, 4
	vlw.v v2, t1
	addi t1, t1, 4
	vlw.v v3, t1
	addi t1, t1, 4
	vlw.v v4, t1
	addi t1, t1, 4
	vlw.v v5, t1
	addi t1, t1, 4
	vlw.v v6, t1
	addi t1, t1, 4
	vlw.v v7, t1
	addi t1, t1, 4
	vlw.v v8, t1
	addi t1, t1, 4
	vlw.v v9, t1
	addi t1, t1, 4
	vlw.v v10, t1
	addi t1, t1, 4
	vlw.v v11, t1
	addi t1, t1, 4
	vlw.v v12, t1
	addi t1, t1, 4
	vlw.v v13, t1
	addi t1, t1, 4
	vlw.v v14, t1
	addi t1, t1, 4
	vlw.v v15, t1
	addi t1, t1, 4
	vlw.v v16, t1
	addi t1, t1, 4
	vlw.v v17, t1
	addi t1, t1, 4
	vlw.v v18, t1
	addi t1, t1, 4
	vlw.v v19, t1
	addi t1, t1, 4
	vlw.v v20, t1
	addi t1, t1, 4
	vlw.v v21, t1
	addi t1, t1, 4
	vlw.v v22, t1
	addi t1, t1, 4
	vlw.v v23, t1
	addi t1, t1, 4
	vlw.v v24, t1
	addi t1, t1, 4
	vlw.v v25, t1
	addi t1, t1, 4
	vlw.v v26, t1
	addi t1, t1, 4
	vlw.v v27, t1
	addi t1, t1, 4
	vlw.v v28, t1
	addi t1, t1, 4
	vlw.v v29, t1
	addi t1, t1, 4
	vlw.v v30, t1
	addi t1, t1, 4
	vlw.v v31, t1
	addi t1, t1, 4
	vdiv.vv v16, v24, v12
	vdiv.vv v0, v8, v4
	vadd.vv v12, v24, v8
	vadd.vv v12, v4, v16
	vadd.vv v16, v16, v0
	vdiv.vv v12, v24, v0
	vsub.vv v20, v0, v8
	vadd.vv v28, v8, v0
	vadd.vv v8, v8, v20
	vsub.vv v4, v12, v12
	la t1, end
	vsw.v v0, t1
	addi t1, t1, 4
	vsw.v v1, t1
	addi t1, t1, 4
	vsw.v v2, t1
	addi t1, t1, 4
	vsw.v v3, t1
	addi t1, t1, 4
	vsw.v v4, t1
	addi t1, t1, 4
	vsw.v v5, t1
	addi t1, t1, 4
	vsw.v v6, t1
	addi t1, t1, 4
	vsw.v v7, t1
	addi t1, t1, 4
	vsw.v v8, t1
	addi t1, t1, 4
	vsw.v v9, t1
	addi t1, t1, 4
	vsw.v v10, t1
	addi t1, t1, 4
	vsw.v v11, t1
	addi t1, t1, 4
	vsw.v v12, t1
	addi t1, t1, 4
	vsw.v v13, t1
	addi t1, t1, 4
	vsw.v v14, t1
	addi t1, t1, 4
	vsw.v v15, t1
	addi t1, t1, 4
	vsw.v v16, t1
	addi t1, t1, 4
	vsw.v v17, t1
	addi t1, t1, 4
	vsw.v v18, t1
	addi t1, t1, 4
	vsw.v v19, t1
	addi t1, t1, 4
	vsw.v v20, t1
	addi t1, t1, 4
	vsw.v v21, t1
	addi t1, t1, 4
	vsw.v v22, t1
	addi t1, t1, 4
	vsw.v v23, t1
	addi t1, t1, 4
	vsw.v v24, t1
	addi t1, t1, 4
	vsw.v v25, t1
	addi t1, t1, 4
	vsw.v v26, t1
	addi t1, t1, 4
	vsw.v v27, t1
	addi t1, t1, 4
	vsw.v v28, t1
	addi t1, t1, 4
	vsw.v v29, t1
	addi t1, t1, 4
	vsw.v v30, t1
	addi t1, t1, 4
	vsw.v v31, t1
	addi t1, t1, 4
	nop

	#==================================================================================================
	# Self-Checks for Test Case 20

	li sp, 0x80022100
	bne sp, t1, fail

	#==================================================================================================
	# Test Case 21 (instruction_rv32v_gen1.rb:101)

	la t1, end
	addi t1, t1, 0
	lw a0, 0(t1)
	lw a1, 4(t1)
	lw a2, 8(t1)
	lw a3, 12(t1)
	lw a4, 16(t1)
	lw a5, 20(t1)
	lw a6, 24(t1)
	lw a7, 28(t1)

	#==================================================================================================
	# Self-Checks for Test Case 21

	li sp, 0x80022080
	bne sp, t1, fail
	bne zero, a0, fail
	bne zero, a1, fail
	ori sp, zero, 1
	bne sp, a2, fail
	not sp, zero
	bne sp, a3, fail
	bne zero, a4, fail
	bne zero, a5, fail
	bne zero, a6, fail
	bne zero, a7, fail

	#==================================================================================================
	# Test Case 22 (instruction_rv32v_gen1.rb:101)

	la t1, end
	addi t1, t1, 32
	lw a0, 0(t1)
	lw a1, 4(t1)
	lw a2, 8(t1)
	lw a3, 12(t1)
	lw a4, 16(t1)
	lw a5, 20(t1)
	lw a6, 24(t1)
	lw a7, 28(t1)

	#==================================================================================================
	# Self-Checks for Test Case 22

	li sp, 0x800220a0
	bne sp, t1, fail
	bne zero, a0, fail
	bne zero, a1, fail
	ori sp, zero, 1
	bne sp, a2, fail
	not sp, zero
	bne sp, a3, fail
	not sp, zero
	bne sp, a4, fail
	not sp, zero
	bne sp, a5, fail
	li sp, 0xfffffffff747f3fc
	bne sp, a6, fail
	li sp, 0x41175ef9
	bne sp, a7, fail

	#==================================================================================================
	# Test Case 23 (instruction_rv32v_gen1.rb:101)

	la t1, end
	addi t1, t1, 64
	lw a0, 0(t1)
	lw a1, 4(t1)
	lw a2, 8(t1)
	lw a3, 12(t1)
	lw a4, 16(t1)
	lw a5, 20(t1)
	lw a6, 24(t1)
	lw a7, 28(t1)

	#==================================================================================================
	# Self-Checks for Test Case 23

	li sp, 0x800220c0
	bne sp, t1, fail
	bne zero, a0, fail
	ori sp, zero, 1
	bne sp, a1, fail
	ori sp, zero, 1
	bne sp, a2, fail
	not sp, zero
	bne sp, a3, fail
	li sp, 0x15f9a4d8
	bne sp, a4, fail
	li sp, 0xffffffffd7af5575
	bne sp, a5, fail
	li sp, 0x5a0da344
	bne sp, a6, fail
	li sp, 0xffffffffa9c1421a
	bne sp, a7, fail

	#==================================================================================================
	# Test Case 24 (instruction_rv32v_gen1.rb:101)

	la t1, end
	addi t1, t1, 96
	lw a0, 0(t1)
	lw a1, 4(t1)
	lw a2, 8(t1)
	lw a3, 12(t1)
	lw a4, 16(t1)
	lw a5, 20(t1)
	lw a6, 24(t1)
	lw a7, 28(t1)

	#==================================================================================================
	# Self-Checks for Test Case 24

	li sp, 0x800220e0
	bne sp, t1, fail
	li sp, 0xffffffffbe896cb7
	bne sp, a0, fail
	li sp, 0x583ab800
	bne sp, a1, fail
	li sp, 0xfffffffff747f3fc
	bne sp, a2, fail
	li sp, 0xffffffffbee8a107
	bne sp, a3, fail
	li sp, 0xffffffffea065b28
	bne sp, a4, fail
	li sp, 0x2850aa8b
	bne sp, a5, fail
	li sp, 0xffffffffa5f25cbe
	bne sp, a6, fail
	li sp, 0x563ebde4
	bne sp, a7, fail

	#==================================================================================================
	# Test Case 25 (instruction_rv32v_gen1.rb:75)

	la t1, data
	vlw.v v0, t1
	addi t1, t1, 4
	vlw.v v1, t1
	addi t1, t1, 4
	vlw.v v2, t1
	addi t1, t1, 4
	vlw.v v3, t1
	addi t1, t1, 4
	vlw.v v4, t1
	addi t1, t1, 4
	vlw.v v5, t1
	addi t1, t1, 4
	vlw.v v6, t1
	addi t1, t1, 4
	vlw.v v7, t1
	addi t1, t1, 4
	vlw.v v8, t1
	addi t1, t1, 4
	vlw.v v9, t1
	addi t1, t1, 4
	vlw.v v10, t1
	addi t1, t1, 4
	vlw.v v11, t1
	addi t1, t1, 4
	vlw.v v12, t1
	addi t1, t1, 4
	vlw.v v13, t1
	addi t1, t1, 4
	vlw.v v14, t1
	addi t1, t1, 4
	vlw.v v15, t1
	addi t1, t1, 4
	vlw.v v16, t1
	addi t1, t1, 4
	vlw.v v17, t1
	addi t1, t1, 4
	vlw.v v18, t1
	addi t1, t1, 4
	vlw.v v19, t1
	addi t1, t1, 4
	vlw.v v20, t1
	addi t1, t1, 4
	vlw.v v21, t1
	addi t1, t1, 4
	vlw.v v22, t1
	addi t1, t1, 4
	vlw.v v23, t1
	addi t1, t1, 4
	vlw.v v24, t1
	addi t1, t1, 4
	vlw.v v25, t1
	addi t1, t1, 4
	vlw.v v26, t1
	addi t1, t1, 4
	vlw.v v27, t1
	addi t1, t1, 4
	vlw.v v28, t1
	addi t1, t1, 4
	vlw.v v29, t1
	addi t1, t1, 4
	vlw.v v30, t1
	addi t1, t1, 4
	vlw.v v31, t1
	addi t1, t1, 4
	vdiv.vv v16, v12, v28
	vsub.vv v20, v16, v20
	vadd.vv v16, v28, v4
	vdiv.vv v28, v12, v16
	vadd.vv v24, v24, v16
	vdiv.vv v0, v8, v12
	vdiv.vv v4, v20, v20
	vsub.vv v20, v0, v0
	vadd.vv v20, v8, v4
	vadd.vv v24, v12, v20
	la t1, end
	vsw.v v0, t1
	addi t1, t1, 4
	vsw.v v1, t1
	addi t1, t1, 4
	vsw.v v2, t1
	addi t1, t1, 4
	vsw.v v3, t1
	addi t1, t1, 4
	vsw.v v4, t1
	addi t1, t1, 4
	vsw.v v5, t1
	addi t1, t1, 4
	vsw.v v6, t1
	addi t1, t1, 4
	vsw.v v7, t1
	addi t1, t1, 4
	vsw.v v8, t1
	addi t1, t1, 4
	vsw.v v9, t1
	addi t1, t1, 4
	vsw.v v10, t1
	addi t1, t1, 4
	vsw.v v11, t1
	addi t1, t1, 4
	vsw.v v12, t1
	addi t1, t1, 4
	vsw.v v13, t1
	addi t1, t1, 4
	vsw.v v14, t1
	addi t1, t1, 4
	vsw.v v15, t1
	addi t1, t1, 4
	vsw.v v16, t1
	addi t1, t1, 4
	vsw.v v17, t1
	addi t1, t1, 4
	vsw.v v18, t1
	addi t1, t1, 4
	vsw.v v19, t1
	addi t1, t1, 4
	vsw.v v20, t1
	addi t1, t1, 4
	vsw.v v21, t1
	addi t1, t1, 4
	vsw.v v22, t1
	addi t1, t1, 4
	vsw.v v23, t1
	addi t1, t1, 4
	vsw.v v24, t1
	addi t1, t1, 4
	vsw.v v25, t1
	addi t1, t1, 4
	vsw.v v26, t1
	addi t1, t1, 4
	vsw.v v27, t1
	addi t1, t1, 4
	vsw.v v28, t1
	addi t1, t1, 4
	vsw.v v29, t1
	addi t1, t1, 4
	vsw.v v30, t1
	addi t1, t1, 4
	vsw.v v31, t1
	addi t1, t1, 4
	nop

	#==================================================================================================
	# Self-Checks for Test Case 25

	li sp, 0x80022100
	bne sp, t1, fail

	#==================================================================================================
	# Test Case 26 (instruction_rv32v_gen1.rb:101)

	la t1, end
	addi t1, t1, 0
	lw a0, 0(t1)
	lw a1, 4(t1)
	lw a2, 8(t1)
	lw a3, 12(t1)
	lw a4, 16(t1)
	lw a5, 20(t1)
	lw a6, 24(t1)
	lw a7, 28(t1)

	#==================================================================================================
	# Self-Checks for Test Case 26

	li sp, 0x80022080
	bne sp, t1, fail
	bne zero, a0, fail
	bne zero, a1, fail
	bne zero, a2, fail
	bne zero, a3, fail
	ori sp, zero, 1
	bne sp, a4, fail
	ori sp, zero, 1
	bne sp, a5, fail
	ori sp, zero, 1
	bne sp, a6, fail
	ori sp, zero, 1
	bne sp, a7, fail

	#==================================================================================================
	# Test Case 27 (instruction_rv32v_gen1.rb:101)

	la t1, end
	addi t1, t1, 32
	lw a0, 0(t1)
	lw a1, 4(t1)
	lw a2, 8(t1)
	lw a3, 12(t1)
	lw a4, 16(t1)
	lw a5, 20(t1)
	lw a6, 24(t1)
	lw a7, 28(t1)

	#==================================================================================================
	# Self-Checks for Test Case 27

	li sp, 0x800220a0
	bne sp, t1, fail
	li sp, 0xffffffffea065b28
	bne sp, a0, fail
	li sp, 0x2850aa8b
	bne sp, a1, fail
	li sp, 0xffffffffa5f25cbd
	bne sp, a2, fail
	li sp, 0x563ebde5
	bne sp, a3, fail
	li sp, 0x6884a2fa
	bne sp, a4, fail
	li sp, 0x523b2453
	bne sp, a5, fail
	li sp, 0x7d9d2f07
	bne sp, a6, fail
	li sp, 0x62210d5a
	bne sp, a7, fail

	#==================================================================================================
	# Test Case 28 (instruction_rv32v_gen1.rb:101)

	la t1, end
	addi t1, t1, 64
	lw a0, 0(t1)
	lw a1, 4(t1)
	lw a2, 8(t1)
	lw a3, 12(t1)
	lw a4, 16(t1)
	lw a5, 20(t1)
	lw a6, 24(t1)
	lw a7, 28(t1)

	#==================================================================================================
	# Self-Checks for Test Case 28

	li sp, 0x800220c0
	bne sp, t1, fail
	li sp, 0x7369a455
	bne sp, a0, fail
	li sp, 0x3b81b6ca
	bne sp, a1, fail
	li sp, 0x682b83ea
	bne sp, a2, fail
	li sp, 0x186bb25a
	bne sp, a3, fail
	li sp, 0xffffffffea065b29
	bne sp, a4, fail
	li sp, 0x2850aa8c
	bne sp, a5, fail
	li sp, 0xffffffffa5f25cbe
	bne sp, a6, fail
	li sp, 0x563ebde6
	bne sp, a7, fail

	#==================================================================================================
	# Test Case 29 (instruction_rv32v_gen1.rb:101)

	la t1, end
	addi t1, t1, 96
	lw a0, 0(t1)
	lw a1, 4(t1)
	lw a2, 8(t1)
	lw a3, 12(t1)
	lw a4, 16(t1)
	lw a5, 20(t1)
	lw a6, 24(t1)
	lw a7, 28(t1)

	#==================================================================================================
	# Self-Checks for Test Case 29

	li sp, 0x800220e0
	bne sp, t1, fail
	li sp, 0x528afe23
	bne sp, a0, fail
	li sp, 0x7a8bcedf
	bne sp, a1, fail
	li sp, 0x238f8bc5
	bne sp, a2, fail
	li sp, 0xffffffffb85fcb40
	bne sp, a3, fail
	bne zero, a4, fail
	ori sp, zero, 1
	bne sp, a5, fail
	ori sp, zero, 1
	bne sp, a6, fail
	ori sp, zero, 4
	bne sp, a7, fail

	#==================================================================================================
	# Test Case 30 (instruction_rv32v_gen1.rb:75)

	la t1, data
	vlw.v v0, t1
	addi t1, t1, 4
	vlw.v v1, t1
	addi t1, t1, 4
	vlw.v v2, t1
	addi t1, t1, 4
	vlw.v v3, t1
	addi t1, t1, 4
	vlw.v v4, t1
	addi t1, t1, 4
	vlw.v v5, t1
	addi t1, t1, 4
	vlw.v v6, t1
	addi t1, t1, 4
	vlw.v v7, t1
	addi t1, t1, 4
	vlw.v v8, t1
	addi t1, t1, 4
	vlw.v v9, t1
	addi t1, t1, 4
	vlw.v v10, t1
	addi t1, t1, 4
	vlw.v v11, t1
	addi t1, t1, 4
	vlw.v v12, t1
	addi t1, t1, 4
	vlw.v v13, t1
	addi t1, t1, 4
	vlw.v v14, t1
	addi t1, t1, 4
	vlw.v v15, t1
	addi t1, t1, 4
	vlw.v v16, t1
	addi t1, t1, 4
	vlw.v v17, t1
	addi t1, t1, 4
	vlw.v v18, t1
	addi t1, t1, 4
	vlw.v v19, t1
	addi t1, t1, 4
	vlw.v v20, t1
	addi t1, t1, 4
	vlw.v v21, t1
	addi t1, t1, 4
	vlw.v v22, t1
	addi t1, t1, 4
	vlw.v v23, t1
	addi t1, t1, 4
	vlw.v v24, t1
	addi t1, t1, 4
	vlw.v v25, t1
	addi t1, t1, 4
	vlw.v v26, t1
	addi t1, t1, 4
	vlw.v v27, t1
	addi t1, t1, 4
	vlw.v v28, t1
	addi t1, t1, 4
	vlw.v v29, t1
	addi t1, t1, 4
	vlw.v v30, t1
	addi t1, t1, 4
	vlw.v v31, t1
	addi t1, t1, 4
	vdiv.vv v0, v0, v20
	vmul.vv v0, v20, v24
	vadd.vv v20, v20, v12
	vdiv.vv v24, v4, v8
	vdiv.vv v4, v0, v20
	vmul.vv v0, v28, v4
	vadd.vv v24, v8, v28
	vdiv.vv v28, v0, v16
	vadd.vv v4, v16, v8
	vadd.vv v8, v16, v8
	la t1, end
	vsw.v v0, t1
	addi t1, t1, 4
	vsw.v v1, t1
	addi t1, t1, 4
	vsw.v v2, t1
	addi t1, t1, 4
	vsw.v v3, t1
	addi t1, t1, 4
	vsw.v v4, t1
	addi t1, t1, 4
	vsw.v v5, t1
	addi t1, t1, 4
	vsw.v v6, t1
	addi t1, t1, 4
	vsw.v v7, t1
	addi t1, t1, 4
	vsw.v v8, t1
	addi t1, t1, 4
	vsw.v v9, t1
	addi t1, t1, 4
	vsw.v v10, t1
	addi t1, t1, 4
	vsw.v v11, t1
	addi t1, t1, 4
	vsw.v v12, t1
	addi t1, t1, 4
	vsw.v v13, t1
	addi t1, t1, 4
	vsw.v v14, t1
	addi t1, t1, 4
	vsw.v v15, t1
	addi t1, t1, 4
	vsw.v v16, t1
	addi t1, t1, 4
	vsw.v v17, t1
	addi t1, t1, 4
	vsw.v v18, t1
	addi t1, t1, 4
	vsw.v v19, t1
	addi t1, t1, 4
	vsw.v v20, t1
	addi t1, t1, 4
	vsw.v v21, t1
	addi t1, t1, 4
	vsw.v v22, t1
	addi t1, t1, 4
	vsw.v v23, t1
	addi t1, t1, 4
	vsw.v v24, t1
	addi t1, t1, 4
	vsw.v v25, t1
	addi t1, t1, 4
	vsw.v v26, t1
	addi t1, t1, 4
	vsw.v v27, t1
	addi t1, t1, 4
	vsw.v v28, t1
	addi t1, t1, 4
	vsw.v v29, t1
	addi t1, t1, 4
	vsw.v v30, t1
	addi t1, t1, 4
	vsw.v v31, t1
	addi t1, t1, 4
	nop

	#==================================================================================================
	# Self-Checks for Test Case 30

	li sp, 0x80022100
	bne sp, t1, fail

	#==================================================================================================
	# Test Case 31 (instruction_rv32v_gen1.rb:101)

	la t1, end
	addi t1, t1, 0
	lw a0, 0(t1)
	lw a1, 4(t1)
	lw a2, 8(t1)
	lw a3, 12(t1)
	lw a4, 16(t1)
	lw a5, 20(t1)
	lw a6, 24(t1)
	lw a7, 28(t1)

	#==================================================================================================
	# Self-Checks for Test Case 31

	li sp, 0x80022080
	bne sp, t1, fail
	li sp, 0xffffffffb20b10c6
	bne sp, a0, fail
	li sp, 0x16f23e58
	bne sp, a1, fail
	bne zero, a2, fail
	bne zero, a3, fail
	li sp, 0xfffffffff7b2d998
	bne sp, a4, fail
	li sp, 0x1aec7434
	bne sp, a5, fail
	li sp, 0xffffffffe3f03e35
	bne sp, a6, fail
	li sp, 0x72615bcb
	bne sp, a7, fail

	#==================================================================================================
	# Test Case 32 (instruction_rv32v_gen1.rb:101)

	la t1, end
	addi t1, t1, 32
	lw a0, 0(t1)
	lw a1, 4(t1)
	lw a2, 8(t1)
	lw a3, 12(t1)
	lw a4, 16(t1)
	lw a5, 20(t1)
	lw a6, 24(t1)
	lw a7, 28(t1)

	#==================================================================================================
	# Self-Checks for Test Case 32

	li sp, 0x800220a0
	bne sp, t1, fail
	li sp, 0xfffffffff7b2d998
	bne sp, a0, fail
	li sp, 0x1aec7434
	bne sp, a1, fail
	li sp, 0xffffffffe3f03e35
	bne sp, a2, fail
	li sp, 0x72615bcb
	bne sp, a3, fail
	li sp, 0x6884a2fa
	bne sp, a4, fail
	li sp, 0x523b2453
	bne sp, a5, fail
	li sp, 0x7d9d2f07
	bne sp, a6, fail
	li sp, 0x62210d5a
	bne sp, a7, fail

	#==================================================================================================
	# Test Case 33 (instruction_rv32v_gen1.rb:101)

	la t1, end
	addi t1, t1, 64
	lw a0, 0(t1)
	lw a1, 4(t1)
	lw a2, 8(t1)
	lw a3, 12(t1)
	lw a4, 16(t1)
	lw a5, 20(t1)
	lw a6, 24(t1)
	lw a7, 28(t1)

	#==================================================================================================
	# Self-Checks for Test Case 33

	li sp, 0x800220c0
	bne sp, t1, fail
	li sp, 0xdac7e70
	bne sp, a0, fail
	li sp, 0xfffffffff29bc9a9
	bne sp, a1, fail
	li sp, 0x3dfde178
	bne sp, a2, fail
	li sp, 0x1c229de6
	bne sp, a3, fail
	li sp, 0x49e2df3f
	bne sp, a4, fail
	li sp, 0x59afebd7
	bne sp, a5, fail
	li sp, 0x26e721b5
	bne sp, a6, fail
	li sp, 0x47018e86
	bne sp, a7, fail

	#==================================================================================================
	# Test Case 34 (instruction_rv32v_gen1.rb:101)

	la t1, end
	addi t1, t1, 96
	lw a0, 0(t1)
	lw a1, 4(t1)
	lw a2, 8(t1)
	lw a3, 12(t1)
	lw a4, 16(t1)
	lw a5, 20(t1)
	lw a6, 24(t1)
	lw a7, 28(t1)

	#==================================================================================================
	# Self-Checks for Test Case 34

	li sp, 0x800220e0
	bne sp, t1, fail
	li sp, 0xffffffff9c116bee
	bne sp, a0, fail
	li sp, 0x115e6c33
	bne sp, a1, fail
	li sp, 0x54bf24f7
	bne sp, a2, fail
	li sp, 0xffffffffb7c14e80
	bne sp, a3, fail
	li sp, 0xfffffffffffffffb
	bne sp, a4, fail
	not sp, zero
	bne sp, a5, fail
	bne zero, a6, fail
	bne zero, a7, fail

	#==================================================================================================
	# Test Case 35 (instruction_rv32v_gen1.rb:75)

	la t1, data
	vlw.v v0, t1
	addi t1, t1, 4
	vlw.v v1, t1
	addi t1, t1, 4
	vlw.v v2, t1
	addi t1, t1, 4
	vlw.v v3, t1
	addi t1, t1, 4
	vlw.v v4, t1
	addi t1, t1, 4
	vlw.v v5, t1
	addi t1, t1, 4
	vlw.v v6, t1
	addi t1, t1, 4
	vlw.v v7, t1
	addi t1, t1, 4
	vlw.v v8, t1
	addi t1, t1, 4
	vlw.v v9, t1
	addi t1, t1, 4
	vlw.v v10, t1
	addi t1, t1, 4
	vlw.v v11, t1
	addi t1, t1, 4
	vlw.v v12, t1
	addi t1, t1, 4
	vlw.v v13, t1
	addi t1, t1, 4
	vlw.v v14, t1
	addi t1, t1, 4
	vlw.v v15, t1
	addi t1, t1, 4
	vlw.v v16, t1
	addi t1, t1, 4
	vlw.v v17, t1
	addi t1, t1, 4
	vlw.v v18, t1
	addi t1, t1, 4
	vlw.v v19, t1
	addi t1, t1, 4
	vlw.v v20, t1
	addi t1, t1, 4
	vlw.v v21, t1
	addi t1, t1, 4
	vlw.v v22, t1
	addi t1, t1, 4
	vlw.v v23, t1
	addi t1, t1, 4
	vlw.v v24, t1
	addi t1, t1, 4
	vlw.v v25, t1
	addi t1, t1, 4
	vlw.v v26, t1
	addi t1, t1, 4
	vlw.v v27, t1
	addi t1, t1, 4
	vlw.v v28, t1
	addi t1, t1, 4
	vlw.v v29, t1
	addi t1, t1, 4
	vlw.v v30, t1
	addi t1, t1, 4
	vlw.v v31, t1
	addi t1, t1, 4
	vsub.vv v28, v0, v16
	vsub.vv v24, v4, v4
	vmul.vv v24, v8, v12
	vdiv.vv v20, v24, v24
	vadd.vv v24, v20, v28
	vadd.vv v12, v0, v8
	vdiv.vv v12, v16, v28
	vdiv.vv v28, v12, v24
	vdiv.vv v20, v16, v28
	vdiv.vv v28, v20, v12
	la t1, end
	vsw.v v0, t1
	addi t1, t1, 4
	vsw.v v1, t1
	addi t1, t1, 4
	vsw.v v2, t1
	addi t1, t1, 4
	vsw.v v3, t1
	addi t1, t1, 4
	vsw.v v4, t1
	addi t1, t1, 4
	vsw.v v5, t1
	addi t1, t1, 4
	vsw.v v6, t1
	addi t1, t1, 4
	vsw.v v7, t1
	addi t1, t1, 4
	vsw.v v8, t1
	addi t1, t1, 4
	vsw.v v9, t1
	addi t1, t1, 4
	vsw.v v10, t1
	addi t1, t1, 4
	vsw.v v11, t1
	addi t1, t1, 4
	vsw.v v12, t1
	addi t1, t1, 4
	vsw.v v13, t1
	addi t1, t1, 4
	vsw.v v14, t1
	addi t1, t1, 4
	vsw.v v15, t1
	addi t1, t1, 4
	vsw.v v16, t1
	addi t1, t1, 4
	vsw.v v17, t1
	addi t1, t1, 4
	vsw.v v18, t1
	addi t1, t1, 4
	vsw.v v19, t1
	addi t1, t1, 4
	vsw.v v20, t1
	addi t1, t1, 4
	vsw.v v21, t1
	addi t1, t1, 4
	vsw.v v22, t1
	addi t1, t1, 4
	vsw.v v23, t1
	addi t1, t1, 4
	vsw.v v24, t1
	addi t1, t1, 4
	vsw.v v25, t1
	addi t1, t1, 4
	vsw.v v26, t1
	addi t1, t1, 4
	vsw.v v27, t1
	addi t1, t1, 4
	vsw.v v28, t1
	addi t1, t1, 4
	vsw.v v29, t1
	addi t1, t1, 4
	vsw.v v30, t1
	addi t1, t1, 4
	vsw.v v31, t1
	addi t1, t1, 4
	nop

	#==================================================================================================
	# Self-Checks for Test Case 35

	li sp, 0x80022100
	bne sp, t1, fail

	#==================================================================================================
	# Test Case 36 (instruction_rv32v_gen1.rb:101)

	la t1, end
	addi t1, t1, 0
	lw a0, 0(t1)
	lw a1, 4(t1)
	lw a2, 8(t1)
	lw a3, 12(t1)
	lw a4, 16(t1)
	lw a5, 20(t1)
	lw a6, 24(t1)
	lw a7, 28(t1)

	#==================================================================================================
	# Self-Checks for Test Case 36

	li sp, 0x80022080
	bne sp, t1, fail
	li sp, 0x58dc02e
	bne sp, a0, fail
	li sp, 0xffffffff99e76af6
	bne sp, a1, fail
	li sp, 0xfffffffff044c4aa
	bne sp, a2, fail
	li sp, 0x46bf6b91
	bne sp, a3, fail
	li sp, 0xffffffffc15e938f
	bne sp, a4, fail
	li sp, 0x5273f522
	bne sp, a5, fail
	li sp, 0xffffffffb95ebbb0
	bne sp, a6, fail
	li sp, 0xffffffffb6e921bf
	bne sp, a7, fail

	#==================================================================================================
	# Test Case 37 (instruction_rv32v_gen1.rb:101)

	la t1, end
	addi t1, t1, 32
	lw a0, 0(t1)
	lw a1, 4(t1)
	lw a2, 8(t1)
	lw a3, 12(t1)
	lw a4, 16(t1)
	lw a5, 20(t1)
	lw a6, 24(t1)
	lw a7, 28(t1)

	#==================================================================================================
	# Self-Checks for Test Case 37

	li sp, 0x800220a0
	bne sp, t1, fail
	li sp, 0xffffffffea065b28
	bne sp, a0, fail
	li sp, 0x2850aa8b
	bne sp, a1, fail
	li sp, 0xffffffffa5f25cbd
	bne sp, a2, fail
	li sp, 0x563ebde5
	bne sp, a3, fail
	not sp, zero
	bne sp, a4, fail
	bne zero, a5, fail
	bne zero, a6, fail
	bne zero, a7, fail

	#==================================================================================================
	# Test Case 38 (instruction_rv32v_gen1.rb:101)

	la t1, end
	addi t1, t1, 64
	lw a0, 0(t1)
	lw a1, 4(t1)
	lw a2, 8(t1)
	lw a3, 12(t1)
	lw a4, 16(t1)
	lw a5, 20(t1)
	lw a6, 24(t1)
	lw a7, 28(t1)

	#==================================================================================================
	# Self-Checks for Test Case 38

	li sp, 0x800220c0
	bne sp, t1, fail
	li sp, 0xdac7e70
	bne sp, a0, fail
	li sp, 0xfffffffff29bc9a9
	bne sp, a1, fail
	li sp, 0x3dfde178
	bne sp, a2, fail
	li sp, 0x1c229de6
	bne sp, a3, fail
	not sp, zero
	bne sp, a4, fail
	not sp, zero
	bne sp, a5, fail
	not sp, zero
	bne sp, a6, fail
	not sp, zero
	bne sp, a7, fail

	#==================================================================================================
	# Test Case 39 (instruction_rv32v_gen1.rb:101)

	la t1, end
	addi t1, t1, 96
	lw a0, 0(t1)
	lw a1, 4(t1)
	lw a2, 8(t1)
	lw a3, 12(t1)
	lw a4, 16(t1)
	lw a5, 20(t1)
	lw a6, 24(t1)
	lw a7, 28(t1)

	#==================================================================================================
	# Self-Checks for Test Case 39

	li sp, 0x800220e0
	bne sp, t1, fail
	li sp, 0xfffffffff7e141bf
	bne sp, a0, fail
	li sp, 0xffffffffa74ba14e
	bne sp, a1, fail
	li sp, 0xffffffffb246e333
	bne sp, a2, fail
	li sp, 0x2a9ccdac
	bne sp, a3, fail
	ori sp, zero, 1
	bne sp, a4, fail
	not sp, zero
	bne sp, a5, fail
	not sp, zero
	bne sp, a6, fail
	not sp, zero
	bne sp, a7, fail

	#==================================================================================================
	# Test Case 40 (instruction_rv32v_gen1.rb:75)

	la t1, data
	vlw.v v0, t1
	addi t1, t1, 4
	vlw.v v1, t1
	addi t1, t1, 4
	vlw.v v2, t1
	addi t1, t1, 4
	vlw.v v3, t1
	addi t1, t1, 4
	vlw.v v4, t1
	addi t1, t1, 4
	vlw.v v5, t1
	addi t1, t1, 4
	vlw.v v6, t1
	addi t1, t1, 4
	vlw.v v7, t1
	addi t1, t1, 4
	vlw.v v8, t1
	addi t1, t1, 4
	vlw.v v9, t1
	addi t1, t1, 4
	vlw.v v10, t1
	addi t1, t1, 4
	vlw.v v11, t1
	addi t1, t1, 4
	vlw.v v12, t1
	addi t1, t1, 4
	vlw.v v13, t1
	addi t1, t1, 4
	vlw.v v14, t1
	addi t1, t1, 4
	vlw.v v15, t1
	addi t1, t1, 4
	vlw.v v16, t1
	addi t1, t1, 4
	vlw.v v17, t1
	addi t1, t1, 4
	vlw.v v18, t1
	addi t1, t1, 4
	vlw.v v19, t1
	addi t1, t1, 4
	vlw.v v20, t1
	addi t1, t1, 4
	vlw.v v21, t1
	addi t1, t1, 4
	vlw.v v22, t1
	addi t1, t1, 4
	vlw.v v23, t1
	addi t1, t1, 4
	vlw.v v24, t1
	addi t1, t1, 4
	vlw.v v25, t1
	addi t1, t1, 4
	vlw.v v26, t1
	addi t1, t1, 4
	vlw.v v27, t1
	addi t1, t1, 4
	vlw.v v28, t1
	addi t1, t1, 4
	vlw.v v29, t1
	addi t1, t1, 4
	vlw.v v30, t1
	addi t1, t1, 4
	vlw.v v31, t1
	addi t1, t1, 4
	vsub.vv v20, v28, v0
	vadd.vv v12, v8, v24
	vadd.vv v20, v16, v24
	vsub.vv v24, v24, v28
	vadd.vv v16, v12, v8
	vmul.vv v4, v0, v12
	vmul.vv v4, v20, v28
	vmul.vv v28, v12, v0
	vadd.vv v16, v12, v4
	vadd.vv v28, v24, v20
	la t1, end
	vsw.v v0, t1
	addi t1, t1, 4
	vsw.v v1, t1
	addi t1, t1, 4
	vsw.v v2, t1
	addi t1, t1, 4
	vsw.v v3, t1
	addi t1, t1, 4
	vsw.v v4, t1
	addi t1, t1, 4
	vsw.v v5, t1
	addi t1, t1, 4
	vsw.v v6, t1
	addi t1, t1, 4
	vsw.v v7, t1
	addi t1, t1, 4
	vsw.v v8, t1
	addi t1, t1, 4
	vsw.v v9, t1
	addi t1, t1, 4
	vsw.v v10, t1
	addi t1, t1, 4
	vsw.v v11, t1
	addi t1, t1, 4
	vsw.v v12, t1
	addi t1, t1, 4
	vsw.v v13, t1
	addi t1, t1, 4
	vsw.v v14, t1
	addi t1, t1, 4
	vsw.v v15, t1
	addi t1, t1, 4
	vsw.v v16, t1
	addi t1, t1, 4
	vsw.v v17, t1
	addi t1, t1, 4
	vsw.v v18, t1
	addi t1, t1, 4
	vsw.v v19, t1
	addi t1, t1, 4
	vsw.v v20, t1
	addi t1, t1, 4
	vsw.v v21, t1
	addi t1, t1, 4
	vsw.v v22, t1
	addi t1, t1, 4
	vsw.v v23, t1
	addi t1, t1, 4
	vsw.v v24, t1
	addi t1, t1, 4
	vsw.v v25, t1
	addi t1, t1, 4
	vsw.v v26, t1
	addi t1, t1, 4
	vsw.v v27, t1
	addi t1, t1, 4
	vsw.v v28, t1
	addi t1, t1, 4
	vsw.v v29, t1
	addi t1, t1, 4
	vsw.v v30, t1
	addi t1, t1, 4
	vsw.v v31, t1
	addi t1, t1, 4
	nop

	#==================================================================================================
	# Self-Checks for Test Case 40

	li sp, 0x80022100
	bne sp, t1, fail

	#==================================================================================================
	# Test Case 41 (instruction_rv32v_gen1.rb:101)

	la t1, end
	addi t1, t1, 0
	lw a0, 0(t1)
	lw a1, 4(t1)
	lw a2, 8(t1)
	lw a3, 12(t1)
	lw a4, 16(t1)
	lw a5, 20(t1)
	lw a6, 24(t1)
	lw a7, 28(t1)

	#==================================================================================================
	# Self-Checks for Test Case 41

	li sp, 0x80022080
	bne sp, t1, fail
	li sp, 0x58dc02e
	bne sp, a0, fail
	li sp, 0xffffffff99e76af6
	bne sp, a1, fail
	li sp, 0xfffffffff044c4aa
	bne sp, a2, fail
	li sp, 0x46bf6b91
	bne sp, a3, fail
	li sp, 0xffffffff8913502a
	bne sp, a4, fail
	li sp, 0x3b1a7fe8
	bne sp, a5, fail
	li sp, 0xffffffff9104fc48
	bne sp, a6, fail
	li sp, 0xffffffffb48e697f
	bne sp, a7, fail

	#==================================================================================================
	# Test Case 42 (instruction_rv32v_gen1.rb:101)

	la t1, end
	addi t1, t1, 32
	lw a0, 0(t1)
	lw a1, 4(t1)
	lw a2, 8(t1)
	lw a3, 12(t1)
	lw a4, 16(t1)
	lw a5, 20(t1)
	lw a6, 24(t1)
	lw a7, 28(t1)

	#==================================================================================================
	# Self-Checks for Test Case 42

	li sp, 0x800220a0
	bne sp, t1, fail
	li sp, 0xffffffffea065b28
	bne sp, a0, fail
	li sp, 0x2850aa8b
	bne sp, a1, fail
	li sp, 0xffffffffa5f25cbd
	bne sp, a2, fail
	li sp, 0x563ebde5
	bne sp, a3, fail
	li sp, 0xffffffffa88fc7df
	bne sp, a4, fail
	li sp, 0xffffffff808b628b
	bne sp, a5, fail
	li sp, 0xffffffff9d3a50b9
	bne sp, a6, fail
	li sp, 0x15275eec
	bne sp, a7, fail

	#==================================================================================================
	# Test Case 43 (instruction_rv32v_gen1.rb:101)

	la t1, end
	addi t1, t1, 64
	lw a0, 0(t1)
	lw a1, 4(t1)
	lw a2, 8(t1)
	lw a3, 12(t1)
	lw a4, 16(t1)
	lw a5, 20(t1)
	lw a6, 24(t1)
	lw a7, 28(t1)

	#==================================================================================================
	# Self-Checks for Test Case 43

	li sp, 0x800220c0
	bne sp, t1, fail
	li sp, 0x31a31809
	bne sp, a0, fail
	li sp, 0xffffffffbba5e273
	bne sp, a1, fail
	li sp, 0x2e3f4d01
	bne sp, a2, fail
	li sp, 0xffffffffc9b5c86b
	bne sp, a3, fail
	li sp, 0xffffffffcc35eb27
	bne sp, a4, fail
	li sp, 0x4ad681a9
	bne sp, a5, fail
	li sp, 0x3545d574
	bne sp, a6, fail
	li sp, 0xffffffffdb0b3eed
	bne sp, a7, fail

	#==================================================================================================
	# Test Case 44 (instruction_rv32v_gen1.rb:101)

	la t1, end
	addi t1, t1, 96
	lw a0, 0(t1)
	lw a1, 4(t1)
	lw a2, 8(t1)
	lw a3, 12(t1)
	lw a4, 16(t1)
	lw a5, 20(t1)
	lw a6, 24(t1)
	lw a7, 28(t1)

	#==================================================================================================
	# Self-Checks for Test Case 44

	li sp, 0x800220e0
	bne sp, t1, fail
	li sp, 0xc7e5bf1
	bne sp, a0, fail
	li sp, 0x6f2cf658
	bne sp, a1, fail
	li sp, 0x487b2bc2
	bne sp, a2, fail
	li sp, 0x5d66106c
	bne sp, a3, fail
	li sp, 0xffffffffd8b44718
	bne sp, a4, fail
	li sp, 0xffffffffba037801
	bne sp, a5, fail
	li sp, 0x7dc10136
	bne sp, a6, fail
	li sp, 0x38714f59
	bne sp, a7, fail

	#==================================================================================================
	# Test Case 45 (instruction_rv32v_gen1.rb:75)

	la t1, data
	vlw.v v0, t1
	addi t1, t1, 4
	vlw.v v1, t1
	addi t1, t1, 4
	vlw.v v2, t1
	addi t1, t1, 4
	vlw.v v3, t1
	addi t1, t1, 4
	vlw.v v4, t1
	addi t1, t1, 4
	vlw.v v5, t1
	addi t1, t1, 4
	vlw.v v6, t1
	addi t1, t1, 4
	vlw.v v7, t1
	addi t1, t1, 4
	vlw.v v8, t1
	addi t1, t1, 4
	vlw.v v9, t1
	addi t1, t1, 4
	vlw.v v10, t1
	addi t1, t1, 4
	vlw.v v11, t1
	addi t1, t1, 4
	vlw.v v12, t1
	addi t1, t1, 4
	vlw.v v13, t1
	addi t1, t1, 4
	vlw.v v14, t1
	addi t1, t1, 4
	vlw.v v15, t1
	addi t1, t1, 4
	vlw.v v16, t1
	addi t1, t1, 4
	vlw.v v17, t1
	addi t1, t1, 4
	vlw.v v18, t1
	addi t1, t1, 4
	vlw.v v19, t1
	addi t1, t1, 4
	vlw.v v20, t1
	addi t1, t1, 4
	vlw.v v21, t1
	addi t1, t1, 4
	vlw.v v22, t1
	addi t1, t1, 4
	vlw.v v23, t1
	addi t1, t1, 4
	vlw.v v24, t1
	addi t1, t1, 4
	vlw.v v25, t1
	addi t1, t1, 4
	vlw.v v26, t1
	addi t1, t1, 4
	vlw.v v27, t1
	addi t1, t1, 4
	vlw.v v28, t1
	addi t1, t1, 4
	vlw.v v29, t1
	addi t1, t1, 4
	vlw.v v30, t1
	addi t1, t1, 4
	vlw.v v31, t1
	addi t1, t1, 4
	vsub.vv v28, v24, v20
	vmul.vv v4, v24, v28
	vadd.vv v0, v28, v8
	vdiv.vv v24, v0, v24
	vsub.vv v4, v20, v16
	vmul.vv v24, v20, v12
	vsub.vv v8, v4, v20
	vsub.vv v0, v24, v4
	vsub.vv v16, v12, v24
	vsub.vv v0, v28, v24
	la t1, end
	vsw.v v0, t1
	addi t1, t1, 4
	vsw.v v1, t1
	addi t1, t1, 4
	vsw.v v2, t1
	addi t1, t1, 4
	vsw.v v3, t1
	addi t1, t1, 4
	vsw.v v4, t1
	addi t1, t1, 4
	vsw.v v5, t1
	addi t1, t1, 4
	vsw.v v6, t1
	addi t1, t1, 4
	vsw.v v7, t1
	addi t1, t1, 4
	vsw.v v8, t1
	addi t1, t1, 4
	vsw.v v9, t1
	addi t1, t1, 4
	vsw.v v10, t1
	addi t1, t1, 4
	vsw.v v11, t1
	addi t1, t1, 4
	vsw.v v12, t1
	addi t1, t1, 4
	vsw.v v13, t1
	addi t1, t1, 4
	vsw.v v14, t1
	addi t1, t1, 4
	vsw.v v15, t1
	addi t1, t1, 4
	vsw.v v16, t1
	addi t1, t1, 4
	vsw.v v17, t1
	addi t1, t1, 4
	vsw.v v18, t1
	addi t1, t1, 4
	vsw.v v19, t1
	addi t1, t1, 4
	vsw.v v20, t1
	addi t1, t1, 4
	vsw.v v21, t1
	addi t1, t1, 4
	vsw.v v22, t1
	addi t1, t1, 4
	vsw.v v23, t1
	addi t1, t1, 4
	vsw.v v24, t1
	addi t1, t1, 4
	vsw.v v25, t1
	addi t1, t1, 4
	vsw.v v26, t1
	addi t1, t1, 4
	vsw.v v27, t1
	addi t1, t1, 4
	vsw.v v28, t1
	addi t1, t1, 4
	vsw.v v29, t1
	addi t1, t1, 4
	vsw.v v30, t1
	addi t1, t1, 4
	vsw.v v31, t1
	addi t1, t1, 4
	nop

	#==================================================================================================
	# Self-Checks for Test Case 45

	li sp, 0x80022100
	bne sp, t1, fail

	#==================================================================================================
	# Test Case 46 (instruction_rv32v_gen1.rb:101)

	la t1, end
	addi t1, t1, 0
	lw a0, 0(t1)
	lw a1, 4(t1)
	lw a2, 8(t1)
	lw a3, 12(t1)
	lw a4, 16(t1)
	lw a5, 20(t1)
	lw a6, 24(t1)
	lw a7, 28(t1)

	#==================================================================================================
	# Self-Checks for Test Case 46

	li sp, 0x80022080
	bne sp, t1, fail
	li sp, 0x96cab10
	bne sp, a0, fail
	li sp, 0x366eb0b0
	bne sp, a1, fail
	li sp, 0x4eb46c8c
	bne sp, a2, fail
	li sp, 0x7ddf7a63
	bne sp, a3, fail
	li sp, 0xffffffffd3b1bdd5
	bne sp, a4, fail
	li sp, 0x14d8fddb
	bne sp, a5, fail
	li sp, 0x6b4c1136
	bne sp, a6, fail
	li sp, 0xffffffffc8bde346
	bne sp, a7, fail

	#==================================================================================================
	# Test Case 47 (instruction_rv32v_gen1.rb:101)

	la t1, end
	addi t1, t1, 32
	lw a0, 0(t1)
	lw a1, 4(t1)
	lw a2, 8(t1)
	lw a3, 12(t1)
	lw a4, 16(t1)
	lw a5, 20(t1)
	lw a6, 24(t1)
	lw a7, 28(t1)

	#==================================================================================================
	# Self-Checks for Test Case 47

	li sp, 0x800220a0
	bne sp, t1, fail
	li sp, 0xfffffffff2538190
	bne sp, a0, fail
	li sp, 0xd643657
	bne sp, a1, fail
	li sp, 0xffffffffc2021e88
	bne sp, a2, fail
	li sp, 0xffffffffe3dd621a
	bne sp, a3, fail
	li sp, 0x6884a2fa
	bne sp, a4, fail
	li sp, 0x523b2453
	bne sp, a5, fail
	li sp, 0x7d9d2f07
	bne sp, a6, fail
	li sp, 0x62210d5a
	bne sp, a7, fail

	#==================================================================================================
	# Test Case 48 (instruction_rv32v_gen1.rb:101)

	la t1, end
	addi t1, t1, 64
	lw a0, 0(t1)
	lw a1, 4(t1)
	lw a2, 8(t1)
	lw a3, 12(t1)
	lw a4, 16(t1)
	lw a5, 20(t1)
	lw a6, 24(t1)
	lw a7, 28(t1)

	#==================================================================================================
	# Self-Checks for Test Case 48

	li sp, 0x800220c0
	bne sp, t1, fail
	li sp, 0xffffffff94c61d98
	bne sp, a0, fail
	li sp, 0x37e3e487
	bne sp, a1, fail
	li sp, 0x7e539a45
	bne sp, a2, fail
	li sp, 0x5f867e2
	bne sp, a3, fail
	li sp, 0xffffffffe15e3c45
	bne sp, a4, fail
	li sp, 0x774c784
	bne sp, a5, fail
	li sp, 0xffffffffa949f2ae
	bne sp, a6, fail
	li sp, 0xffffffffe4e0812c
	bne sp, a7, fail

	#==================================================================================================
	# Test Case 49 (instruction_rv32v_gen1.rb:101)

	la t1, end
	addi t1, t1, 96
	lw a0, 0(t1)
	lw a1, 4(t1)
	lw a2, 8(t1)
	lw a3, 12(t1)
	lw a4, 16(t1)
	lw a5, 20(t1)
	lw a6, 24(t1)
	lw a7, 28(t1)

	#==================================================================================================
	# Self-Checks for Test Case 49

	li sp, 0x800220e0
	bne sp, t1, fail
	li sp, 0xffffffffd3be8562
	bne sp, a0, fail
	li sp, 0x1a573fcc
	bne sp, a1, fail
	li sp, 0xffffffffff4994c2
	bne sp, a2, fail
	li sp, 0x5c28a578
	bne sp, a3, fail
	li sp, 0xffffffffdd2b3072
	bne sp, a4, fail
	li sp, 0x50c5f07c
	bne sp, a5, fail
	li sp, 0x4dfe014e
	bne sp, a6, fail
	li sp, 0xffffffffda081fdb
	bne sp, a7, fail

	#==================================================================================================
	# Epilogue (riscv_base.rb:291)

	j pass
fail:
	fence
1:
	beqz gp, 1b
	sll gp, gp, ra
	or gp, gp, ra
	ecall
pass:
	fence
	li gp, 0x1
	ecall
	unimp

	#==================================================================================================
	# Data

	#============================================= .data ==============================================
	.data

	#========================================== Global Data ===========================================
	.align 4
	.pushsection .tohost,"aw",@progbits
	.align 8; .global tohost; tohost: .dword 0;
	.align 8; .global fromhost; fromhost: .dword 0;
	.popsection;
	.align 4
	.globl begin_signature
begin_signature:

data:
	.word 0x58DC02E, 0x99E76AF6
	.word 0xF044C4AA, 0x46BF6B91
	.word 0xC15E938F, 0x5273F522
	.word 0xB95EBBB0, 0xB6E921BF
	.word 0xEA065B28, 0x2850AA8B
	.word 0xA5F25CBD, 0x563EBDE5
	.word 0x6884A2FA, 0x523B2453
	.word 0x7D9D2F07, 0x62210D5A
	.word 0xDAC7E70, 0xF29BC9A9
	.word 0x3DFDE178, 0x1C229DE6
	.word 0xE15E3C45, 0x774C784
	.word 0xA949F2AE, 0xE4E0812C
	.word 0xBE896CB7, 0x583AB800
	.word 0xF747F3FC, 0xBEE8A107
	.word 0xB20B10C6, 0xE90DC1A8
	.word 0xAECCC83A, 0x6182909B
end:
	.skip 1

	.align 4
	.globl end_signature
end_signature:
	.align 8; .global begin_regstate; begin_regstate:
	.word 128;
	.align 8; .global end_regstate; end_regstate:
	.word 4;
