	#==================================================================================================
	#
	# This test program was automatically generated by the MicroTESK tool
	# Generation started: Mon Oct 21 18:21:25 MSK 2019
	#
	# Ivannikov Institute for System Programming of the Russian Academy of Sciences (ISP RAS)
	# 25 Alexander Solzhenitsyn st., Moscow, 109004, Russia
	#
	# http://www.microtesk.org
	# http://forge.ispras.ru/projects/microtesk
	#
	#==================================================================================================

	#==================================================================================================
	# Prologue (riscv_test.rb:231)

	#====================================== .section .text.init =======================================
	.section .text.init
	.align 6
	.weak stvec_handler
	.weak mtvec_handler
	.globl _start
_start:
	j reset_vector
	.align 2
trap_vector:
	csrr t5, mcause
	li t6, 0x8
	beq t5, t6, write_tohost
	li t6, 0x9
	beq t5, t6, write_tohost
	li t6, 0xb
	beq t5, t6, write_tohost
	la t5, mtvec_handler
	beqz t5, 1f
	jr t5
1:
	csrr t5, mcause
	bgez t5, handle_exception
	j other_exception
handle_exception:
other_exception:
1:
	ori gp, gp, 1337
write_tohost:
	nop
	sw gp, tohost, t5
	nop
	j write_tohost
reset_vector:
	csrr a0, mhartid
1:
	bnez a0, 1b
	la t0, 1f
	csrw mtvec, t0
	csrwi satp, 0x0
	.align 2
1:
	la t0, 1f
	csrw mtvec, t0
	li t0, 0xffffffffffffffff
	csrw pmpaddr0, t0
	li t0, 0x1f
	csrw pmpcfg0, t0
	.align 2
1:
	la t0, 1f
	csrw mtvec, t0
	csrwi medeleg, 0x0
	csrwi mideleg, 0x0
	csrwi mie, 0x0
	.align 2
1:
	li gp, 0x0
	la t0, trap_vector
	csrw mtvec, t0
	li a0, 0x1
	slli a0, a0, 0x1f
	bgez a0, 1f
	fence
	li gp, 0x1
	ecall
1:
	la t0, stvec_handler
	beqz t0, 1f
	csrw stvec, t0
	li t0, 0xb109
	csrw medeleg, t0
	csrr t1, medeleg
	bne t0, t1, other_exception
1:
	csrwi mstatus, 0x0
	la t0, 1f
	csrw mepc, t0
	csrr a0, mhartid
	mret
1:

	#==================================================================================================
	# External Code (instruction_rv32v_gen1.rb:63)

	addi a0, zero, 32
	vsetvli t0, a0, e32, m4

	#==================================================================================================
	# Test Case 0 (instruction_rv32v_gen1.rb:75)

	la t1, data
	vlw.v v0, (t1)
	addi t1, t1, 16
	vlw.v v4, (t1)
	addi t1, t1, 16
	vlw.v v8, (t1)
	addi t1, t1, 16
	vlw.v v12, (t1)
	addi t1, t1, 16
	vlw.v v16, (t1)
	addi t1, t1, 16
	vlw.v v20, (t1)
	addi t1, t1, 16
	vlw.v v24, (t1)
	addi t1, t1, 16
	vlw.v v28, (t1)
	addi t1, t1, 16
	vmulh.vv v0, v12, v4
	vmul.vv v28, v12, v4
	vmul.vv v24, v16, v12
	vdiv.vv v16, v8, v20
	vsub.vv v24, v24, v0
	vsub.vv v0, v12, v28
	vadd.vv v4, v8, v20
	vdiv.vv v4, v4, v20
	vmul.vv v0, v12, v4
	vadd.vv v24, v8, v20
	la t1, end
	vsw.v v0, (t1)
	addi t1, t1, 16
	vsw.v v4, (t1)
	addi t1, t1, 16
	vsw.v v8, (t1)
	addi t1, t1, 16
	vsw.v v12, (t1)
	addi t1, t1, 16
	vsw.v v16, (t1)
	addi t1, t1, 16
	vsw.v v20, (t1)
	addi t1, t1, 16
	vsw.v v24, (t1)
	addi t1, t1, 16
	vsw.v v28, (t1)
	addi t1, t1, 16
	nop

	#==================================================================================================
	# Self-Checks for Test Case 0

	li sp, 0x80022100
	bne sp, t1, fail

	#==================================================================================================
	# Test Case 1 (instruction_rv32v_gen1.rb:107)

	la t1, end
	addi t1, t1, 0
	lw a0, 0(t1)
	lw a1, 4(t1)
	lw a2, 8(t1)
	lw a3, 12(t1)
	lw a4, 16(t1)
	lw a5, 20(t1)
	lw a6, 24(t1)
	lw a7, 28(t1)

	#==================================================================================================
	# Self-Checks for Test Case 1

	li sp, 0x80022080
	bne sp, t1, fail
	li sp, 0x6884a2fa
	bne sp, a0, fail
	li sp, 0xffffffffed62d9f2
	bne sp, a1, fail
	bne zero, a2, fail
	li sp, 0x3bbde54c
	bne sp, a3, fail
	ori sp, zero, 1
	bne sp, a4, fail
	ori sp, zero, 6
	bne sp, a5, fail
	bne zero, a6, fail
	li sp, 0xfffffffffffffffe
	bne sp, a7, fail

	#==================================================================================================
	# Test Case 2 (instruction_rv32v_gen1.rb:107)

	la t1, end
	addi t1, t1, 32
	lw a0, 0(t1)
	lw a1, 4(t1)
	lw a2, 8(t1)
	lw a3, 12(t1)
	lw a4, 16(t1)
	lw a5, 20(t1)
	lw a6, 24(t1)
	lw a7, 28(t1)

	#==================================================================================================
	# Self-Checks for Test Case 2

	li sp, 0x800220a0
	bne sp, t1, fail
	li sp, 0xffffffffea065b28
	bne sp, a0, fail
	li sp, 0x2850aa8b
	bne sp, a1, fail
	li sp, 0xffffffffa5f25cbd
	bne sp, a2, fail
	li sp, 0x563ebde5
	bne sp, a3, fail
	li sp, 0x6884a2fa
	bne sp, a4, fail
	li sp, 0x523b2453
	bne sp, a5, fail
	li sp, 0x7d9d2f07
	bne sp, a6, fail
	li sp, 0x62210d5a
	bne sp, a7, fail

	#==================================================================================================
	# Test Case 3 (instruction_rv32v_gen1.rb:107)

	la t1, end
	addi t1, t1, 64
	lw a0, 0(t1)
	lw a1, 4(t1)
	lw a2, 8(t1)
	lw a3, 12(t1)
	lw a4, 16(t1)
	lw a5, 20(t1)
	lw a6, 24(t1)
	lw a7, 28(t1)

	#==================================================================================================
	# Self-Checks for Test Case 3

	li sp, 0x800220c0
	bne sp, t1, fail
	bne zero, a0, fail
	ori sp, zero, 5
	bne sp, a1, fail
	ori sp, zero, 1
	bne sp, a2, fail
	li sp, 0xfffffffffffffffd
	bne sp, a3, fail
	li sp, 0xffffffffe15e3c45
	bne sp, a4, fail
	li sp, 0x774c784
	bne sp, a5, fail
	li sp, 0xffffffffa949f2ae
	bne sp, a6, fail
	li sp, 0xffffffffe4e0812c
	bne sp, a7, fail

	#==================================================================================================
	# Test Case 4 (instruction_rv32v_gen1.rb:107)

	la t1, end
	addi t1, t1, 96
	lw a0, 0(t1)
	lw a1, 4(t1)
	lw a2, 8(t1)
	lw a3, 12(t1)
	lw a4, 16(t1)
	lw a5, 20(t1)
	lw a6, 24(t1)
	lw a7, 28(t1)

	#==================================================================================================
	# Self-Checks for Test Case 4

	li sp, 0x800220e0
	bne sp, t1, fail
	li sp, 0xffffffffcb64976d
	bne sp, a0, fail
	li sp, 0x2fc5720f
	bne sp, a1, fail
	li sp, 0x4f3c4f6b
	bne sp, a2, fail
	li sp, 0x3b1f3f11
	bne sp, a3, fail
	li sp, 0xffffffffdd7897a6
	bne sp, a4, fail
	li sp, 0x6ce74206
	bne sp, a5, fail
	li sp, 0xffffffff80fc71d0
	bne sp, a6, fail
	li sp, 0xffffffff9c4b9026
	bne sp, a7, fail

	#==================================================================================================
	# Test Case 5 (instruction_rv32v_gen1.rb:75)

	la t1, data
	vlw.v v0, (t1)
	addi t1, t1, 16
	vlw.v v4, (t1)
	addi t1, t1, 16
	vlw.v v8, (t1)
	addi t1, t1, 16
	vlw.v v12, (t1)
	addi t1, t1, 16
	vlw.v v16, (t1)
	addi t1, t1, 16
	vlw.v v20, (t1)
	addi t1, t1, 16
	vlw.v v24, (t1)
	addi t1, t1, 16
	vlw.v v28, (t1)
	addi t1, t1, 16
	vdiv.vv v12, v20, v20
	vsub.vv v12, v24, v28
	vsub.vv v8, v0, v24
	vsub.vv v12, v8, v4
	vsub.vv v12, v8, v16
	vmulh.vv v20, v16, v24
	vmulh.vv v24, v8, v4
	vdiv.vv v8, v24, v4
	vmul.vv v16, v12, v12
	vmulh.vv v20, v12, v4
	la t1, end
	vsw.v v0, (t1)
	addi t1, t1, 16
	vsw.v v4, (t1)
	addi t1, t1, 16
	vsw.v v8, (t1)
	addi t1, t1, 16
	vsw.v v12, (t1)
	addi t1, t1, 16
	vsw.v v16, (t1)
	addi t1, t1, 16
	vsw.v v20, (t1)
	addi t1, t1, 16
	vsw.v v24, (t1)
	addi t1, t1, 16
	vsw.v v28, (t1)
	addi t1, t1, 16
	nop

	#==================================================================================================
	# Self-Checks for Test Case 5

	li sp, 0x80022100
	bne sp, t1, fail

	#==================================================================================================
	# Test Case 6 (instruction_rv32v_gen1.rb:107)

	la t1, end
	addi t1, t1, 0
	lw a0, 0(t1)
	lw a1, 4(t1)
	lw a2, 8(t1)
	lw a3, 12(t1)
	lw a4, 16(t1)
	lw a5, 20(t1)
	lw a6, 24(t1)
	lw a7, 28(t1)

	#==================================================================================================
	# Self-Checks for Test Case 6

	li sp, 0x80022080
	bne sp, t1, fail
	li sp, 0x58dc02e
	bne sp, a0, fail
	li sp, 0xffffffff99e76af6
	bne sp, a1, fail
	li sp, 0xfffffffff044c4aa
	bne sp, a2, fail
	li sp, 0x46bf6b91
	bne sp, a3, fail
	li sp, 0xffffffffc15e938f
	bne sp, a4, fail
	li sp, 0x5273f522
	bne sp, a5, fail
	li sp, 0xffffffffb95ebbb0
	bne sp, a6, fail
	li sp, 0xffffffffb6e921bf
	bne sp, a7, fail

	#==================================================================================================
	# Test Case 7 (instruction_rv32v_gen1.rb:107)

	la t1, end
	addi t1, t1, 32
	lw a0, 0(t1)
	lw a1, 4(t1)
	lw a2, 8(t1)
	lw a3, 12(t1)
	lw a4, 16(t1)
	lw a5, 20(t1)
	lw a6, 24(t1)
	lw a7, 28(t1)

	#==================================================================================================
	# Self-Checks for Test Case 7

	li sp, 0x800220a0
	bne sp, t1, fail
	bne zero, a0, fail
	bne zero, a1, fail
	bne zero, a2, fail
	bne zero, a3, fail
	li sp, 0x3957d507
	bne sp, a4, fail
	li sp, 0x4f10e94d
	bne sp, a5, fail
	li sp, 0xffffffffbafeef36
	bne sp, a6, fail
	li sp, 0x6bb42ca4
	bne sp, a7, fail

	#==================================================================================================
	# Test Case 8 (instruction_rv32v_gen1.rb:107)

	la t1, end
	addi t1, t1, 64
	lw a0, 0(t1)
	lw a1, 4(t1)
	lw a2, 8(t1)
	lw a3, 12(t1)
	lw a4, 16(t1)
	lw a5, 20(t1)
	lw a6, 24(t1)
	lw a7, 28(t1)

	#==================================================================================================
	# Self-Checks for Test Case 8

	li sp, 0x800220c0
	bne sp, t1, fail
	li sp, 0xffffffff9a06a631
	bne sp, a0, fail
	li sp, 0xffffffff843d4129
	bne sp, a1, fail
	li sp, 0x6addf64
	bne sp, a2, fail
	li sp, 0xffffffffe668c910
	bne sp, a3, fail
	li sp, 0xfffffffff1f891e0
	bne sp, a4, fail
	li sp, 0x19773b09
	bne sp, a5, fail
	li sp, 0x1309c2ac
	bne sp, a6, fail
	li sp, 0xffffffffe1400047
	bne sp, a7, fail

	#==================================================================================================
	# Test Case 9 (instruction_rv32v_gen1.rb:107)

	la t1, end
	addi t1, t1, 96
	lw a0, 0(t1)
	lw a1, 4(t1)
	lw a2, 8(t1)
	lw a3, 12(t1)
	lw a4, 16(t1)
	lw a5, 20(t1)
	lw a6, 24(t1)
	lw a7, 28(t1)

	#==================================================================================================
	# Self-Checks for Test Case 9

	li sp, 0x800220e0
	bne sp, t1, fail
	li sp, 0xffffffffeea02bfb
	bne sp, a0, fail
	li sp, 0x152710ca
	bne sp, a1, fail
	li sp, 0x1ef49d0
	bne sp, a2, fail
	li sp, 0x224e7c1b
	bne sp, a3, fail
	li sp, 0xffffffffb20b10c6
	bne sp, a4, fail
	li sp, 0xffffffffe90dc1a8
	bne sp, a5, fail
	li sp, 0xffffffffaeccc83a
	bne sp, a6, fail
	li sp, 0x6182909b
	bne sp, a7, fail

	#==================================================================================================
	# Test Case 10 (instruction_rv32v_gen1.rb:75)

	la t1, data
	vlw.v v0, (t1)
	addi t1, t1, 16
	vlw.v v4, (t1)
	addi t1, t1, 16
	vlw.v v8, (t1)
	addi t1, t1, 16
	vlw.v v12, (t1)
	addi t1, t1, 16
	vlw.v v16, (t1)
	addi t1, t1, 16
	vlw.v v20, (t1)
	addi t1, t1, 16
	vlw.v v24, (t1)
	addi t1, t1, 16
	vlw.v v28, (t1)
	addi t1, t1, 16
	vsub.vv v4, v16, v16
	vmul.vv v12, v20, v8
	vmul.vv v24, v8, v16
	vdiv.vv v0, v8, v4
	vdiv.vv v16, v28, v8
	vsub.vv v0, v4, v12
	vmulh.vv v24, v16, v16
	vmul.vv v16, v24, v20
	vdiv.vv v0, v28, v8
	vadd.vv v28, v12, v4
	la t1, end
	vsw.v v0, (t1)
	addi t1, t1, 16
	vsw.v v4, (t1)
	addi t1, t1, 16
	vsw.v v8, (t1)
	addi t1, t1, 16
	vsw.v v12, (t1)
	addi t1, t1, 16
	vsw.v v16, (t1)
	addi t1, t1, 16
	vsw.v v20, (t1)
	addi t1, t1, 16
	vsw.v v24, (t1)
	addi t1, t1, 16
	vsw.v v28, (t1)
	addi t1, t1, 16
	nop

	#==================================================================================================
	# Self-Checks for Test Case 10

	li sp, 0x80022100
	bne sp, t1, fail

	#==================================================================================================
	# Test Case 11 (instruction_rv32v_gen1.rb:107)

	la t1, end
	addi t1, t1, 0
	lw a0, 0(t1)
	lw a1, 4(t1)
	lw a2, 8(t1)
	lw a3, 12(t1)
	lw a4, 16(t1)
	lw a5, 20(t1)
	lw a6, 24(t1)
	lw a7, 28(t1)

	#==================================================================================================
	# Self-Checks for Test Case 11

	li sp, 0x80022080
	bne sp, t1, fail
	ori sp, zero, 3
	bne sp, a0, fail
	bne zero, a1, fail
	bne zero, a2, fail
	ori sp, zero, 1
	bne sp, a3, fail
	bne zero, a4, fail
	bne zero, a5, fail
	bne zero, a6, fail
	bne zero, a7, fail

	#==================================================================================================
	# Test Case 12 (instruction_rv32v_gen1.rb:107)

	la t1, end
	addi t1, t1, 32
	lw a0, 0(t1)
	lw a1, 4(t1)
	lw a2, 8(t1)
	lw a3, 12(t1)
	lw a4, 16(t1)
	lw a5, 20(t1)
	lw a6, 24(t1)
	lw a7, 28(t1)

	#==================================================================================================
	# Self-Checks for Test Case 12

	li sp, 0x800220a0
	bne sp, t1, fail
	li sp, 0xffffffffea065b28
	bne sp, a0, fail
	li sp, 0x2850aa8b
	bne sp, a1, fail
	li sp, 0xffffffffa5f25cbd
	bne sp, a2, fail
	li sp, 0x563ebde5
	bne sp, a3, fail
	li sp, 0x31c3f1c8
	bne sp, a4, fail
	li sp, 0xffffffff9225fcac
	bne sp, a5, fail
	li sp, 0x1d4ab276
	bne sp, a6, fail
	li sp, 0xffffffff8cd9085c
	bne sp, a7, fail

	#==================================================================================================
	# Test Case 13 (instruction_rv32v_gen1.rb:107)

	la t1, end
	addi t1, t1, 64
	lw a0, 0(t1)
	lw a1, 4(t1)
	lw a2, 8(t1)
	lw a3, 12(t1)
	lw a4, 16(t1)
	lw a5, 20(t1)
	lw a6, 24(t1)
	lw a7, 28(t1)

	#==================================================================================================
	# Self-Checks for Test Case 13

	li sp, 0x800220c0
	bne sp, t1, fail
	bne zero, a0, fail
	bne zero, a1, fail
	bne zero, a2, fail
	bne zero, a3, fail
	li sp, 0xffffffffe15e3c45
	bne sp, a4, fail
	li sp, 0x774c784
	bne sp, a5, fail
	li sp, 0xffffffffa949f2ae
	bne sp, a6, fail
	li sp, 0xffffffffe4e0812c
	bne sp, a7, fail

	#==================================================================================================
	# Test Case 14 (instruction_rv32v_gen1.rb:107)

	la t1, end
	addi t1, t1, 96
	lw a0, 0(t1)
	lw a1, 4(t1)
	lw a2, 8(t1)
	lw a3, 12(t1)
	lw a4, 16(t1)
	lw a5, 20(t1)
	lw a6, 24(t1)
	lw a7, 28(t1)

	#==================================================================================================
	# Self-Checks for Test Case 14

	li sp, 0x800220e0
	bne sp, t1, fail
	bne zero, a0, fail
	bne zero, a1, fail
	bne zero, a2, fail
	bne zero, a3, fail
	li sp, 0x31c3f1c8
	bne sp, a4, fail
	li sp, 0xffffffff9225fcac
	bne sp, a5, fail
	li sp, 0x1d4ab276
	bne sp, a6, fail
	li sp, 0xffffffff8cd9085c
	bne sp, a7, fail

	#==================================================================================================
	# Test Case 15 (instruction_rv32v_gen1.rb:75)

	la t1, data
	vlw.v v0, (t1)
	addi t1, t1, 16
	vlw.v v4, (t1)
	addi t1, t1, 16
	vlw.v v8, (t1)
	addi t1, t1, 16
	vlw.v v12, (t1)
	addi t1, t1, 16
	vlw.v v16, (t1)
	addi t1, t1, 16
	vlw.v v20, (t1)
	addi t1, t1, 16
	vlw.v v24, (t1)
	addi t1, t1, 16
	vlw.v v28, (t1)
	addi t1, t1, 16
	vmulh.vv v8, v16, v16
	vmulh.vv v24, v12, v16
	vmulh.vv v0, v4, v12
	vdiv.vv v0, v4, v16
	vadd.vv v28, v28, v8
	vmul.vv v28, v0, v16
	vdiv.vv v12, v12, v12
	vmul.vv v28, v16, v0
	vmulh.vv v4, v28, v20
	vmulh.vv v8, v16, v8
	la t1, end
	vsw.v v0, (t1)
	addi t1, t1, 16
	vsw.v v4, (t1)
	addi t1, t1, 16
	vsw.v v8, (t1)
	addi t1, t1, 16
	vsw.v v12, (t1)
	addi t1, t1, 16
	vsw.v v16, (t1)
	addi t1, t1, 16
	vsw.v v20, (t1)
	addi t1, t1, 16
	vsw.v v24, (t1)
	addi t1, t1, 16
	vsw.v v28, (t1)
	addi t1, t1, 16
	nop

	#==================================================================================================
	# Self-Checks for Test Case 15

	li sp, 0x80022100
	bne sp, t1, fail

	#==================================================================================================
	# Test Case 16 (instruction_rv32v_gen1.rb:107)

	la t1, end
	addi t1, t1, 0
	lw a0, 0(t1)
	lw a1, 4(t1)
	lw a2, 8(t1)
	lw a3, 12(t1)
	lw a4, 16(t1)
	lw a5, 20(t1)
	lw a6, 24(t1)
	lw a7, 28(t1)

	#==================================================================================================
	# Self-Checks for Test Case 16

	li sp, 0x80022080
	bne sp, t1, fail
	li sp, 0xfffffffffffffffc
	bne sp, a0, fail
	li sp, 0xfffffffffffffffa
	bne sp, a1, fail
	not sp, zero
	bne sp, a2, fail
	li sp, 0xfffffffffffffffe
	bne sp, a3, fail
	li sp, 0x68b6b04
	bne sp, a4, fail
	li sp, 0x25717fc
	bne sp, a5, fail
	li sp, 0x14ff5f76
	bne sp, a6, fail
	li sp, 0x5f63991
	bne sp, a7, fail

	#==================================================================================================
	# Test Case 17 (instruction_rv32v_gen1.rb:107)

	la t1, end
	addi t1, t1, 32
	lw a0, 0(t1)
	lw a1, 4(t1)
	lw a2, 8(t1)
	lw a3, 12(t1)
	lw a4, 16(t1)
	lw a5, 20(t1)
	lw a6, 24(t1)
	lw a7, 28(t1)

	#==================================================================================================
	# Self-Checks for Test Case 17

	li sp, 0x800220a0
	bne sp, t1, fail
	li sp, 0x9fca1
	bne sp, a0, fail
	li sp, 0xfffffffffff69e7f
	bne sp, a1, fail
	li sp, 0x3a2988b
	bne sp, a2, fail
	li sp, 0x56ff94
	bne sp, a3, fail
	ori sp, zero, 1
	bne sp, a4, fail
	ori sp, zero, 1
	bne sp, a5, fail
	ori sp, zero, 1
	bne sp, a6, fail
	ori sp, zero, 1
	bne sp, a7, fail

	#==================================================================================================
	# Test Case 18 (instruction_rv32v_gen1.rb:107)

	la t1, end
	addi t1, t1, 64
	lw a0, 0(t1)
	lw a1, 4(t1)
	lw a2, 8(t1)
	lw a3, 12(t1)
	lw a4, 16(t1)
	lw a5, 20(t1)
	lw a6, 24(t1)
	lw a7, 28(t1)

	#==================================================================================================
	# Self-Checks for Test Case 18

	li sp, 0x800220c0
	bne sp, t1, fail
	li sp, 0xdac7e70
	bne sp, a0, fail
	li sp, 0xfffffffff29bc9a9
	bne sp, a1, fail
	li sp, 0x3dfde178
	bne sp, a2, fail
	li sp, 0x1c229de6
	bne sp, a3, fail
	li sp, 0xffffffffe15e3c45
	bne sp, a4, fail
	li sp, 0x774c784
	bne sp, a5, fail
	li sp, 0xffffffffa949f2ae
	bne sp, a6, fail
	li sp, 0xffffffffe4e0812c
	bne sp, a7, fail

	#==================================================================================================
	# Test Case 19 (instruction_rv32v_gen1.rb:107)

	la t1, end
	addi t1, t1, 96
	lw a0, 0(t1)
	lw a1, 4(t1)
	lw a2, 8(t1)
	lw a3, 12(t1)
	lw a4, 16(t1)
	lw a5, 20(t1)
	lw a6, 24(t1)
	lw a7, 28(t1)

	#==================================================================================================
	# Self-Checks for Test Case 19

	li sp, 0x800220e0
	bne sp, t1, fail
	li sp, 0x5952903
	bne sp, a0, fail
	li sp, 0xfffffffffbb2ce99
	bne sp, a1, fail
	li sp, 0x1e6b072e
	bne sp, a2, fail
	li sp, 0xac8e260
	bne sp, a3, fail
	li sp, 0xffffffffc94e0640
	bne sp, a4, fail
	li sp, 0x5059460a
	bne sp, a5, fail
	li sp, 0xffffffffc2021e88
	bne sp, a6, fail
	li sp, 0xffffffffc7bac434
	bne sp, a7, fail

	#==================================================================================================
	# Test Case 20 (instruction_rv32v_gen1.rb:75)

	la t1, data
	vlw.v v0, (t1)
	addi t1, t1, 16
	vlw.v v4, (t1)
	addi t1, t1, 16
	vlw.v v8, (t1)
	addi t1, t1, 16
	vlw.v v12, (t1)
	addi t1, t1, 16
	vlw.v v16, (t1)
	addi t1, t1, 16
	vlw.v v20, (t1)
	addi t1, t1, 16
	vlw.v v24, (t1)
	addi t1, t1, 16
	vlw.v v28, (t1)
	addi t1, t1, 16
	vmul.vv v8, v8, v20
	vmul.vv v4, v20, v24
	vsub.vv v24, v16, v0
	vmulh.vv v24, v16, v24
	vmulh.vv v8, v8, v24
	vmul.vv v24, v0, v28
	vdiv.vv v16, v4, v8
	vsub.vv v12, v16, v28
	vmul.vv v24, v20, v8
	vmul.vv v20, v0, v20
	la t1, end
	vsw.v v0, (t1)
	addi t1, t1, 16
	vsw.v v4, (t1)
	addi t1, t1, 16
	vsw.v v8, (t1)
	addi t1, t1, 16
	vsw.v v12, (t1)
	addi t1, t1, 16
	vsw.v v16, (t1)
	addi t1, t1, 16
	vsw.v v20, (t1)
	addi t1, t1, 16
	vsw.v v24, (t1)
	addi t1, t1, 16
	vsw.v v28, (t1)
	addi t1, t1, 16
	nop

	#==================================================================================================
	# Self-Checks for Test Case 20

	li sp, 0x80022100
	bne sp, t1, fail

	#==================================================================================================
	# Test Case 21 (instruction_rv32v_gen1.rb:107)

	la t1, end
	addi t1, t1, 0
	lw a0, 0(t1)
	lw a1, 4(t1)
	lw a2, 8(t1)
	lw a3, 12(t1)
	lw a4, 16(t1)
	lw a5, 20(t1)
	lw a6, 24(t1)
	lw a7, 28(t1)

	#==================================================================================================
	# Self-Checks for Test Case 21

	li sp, 0x80022080
	bne sp, t1, fail
	li sp, 0x58dc02e
	bne sp, a0, fail
	li sp, 0xffffffff99e76af6
	bne sp, a1, fail
	li sp, 0xfffffffff044c4aa
	bne sp, a2, fail
	li sp, 0x46bf6b91
	bne sp, a3, fail
	li sp, 0x52b73153
	bne sp, a4, fail
	li sp, 0xffffffff834ee000
	bne sp, a5, fail
	li sp, 0x6680d48
	bne sp, a6, fail
	li sp, 0x2b403434
	bne sp, a7, fail

	#==================================================================================================
	# Test Case 22 (instruction_rv32v_gen1.rb:107)

	la t1, end
	addi t1, t1, 32
	lw a0, 0(t1)
	lw a1, 4(t1)
	lw a2, 8(t1)
	lw a3, 12(t1)
	lw a4, 16(t1)
	lw a5, 20(t1)
	lw a6, 24(t1)
	lw a7, 28(t1)

	#==================================================================================================
	# Self-Checks for Test Case 22

	li sp, 0x800220a0
	bne sp, t1, fail
	li sp, 0x159594
	bne sp, a0, fail
	li sp, 0x1fdbae2
	bne sp, a1, fail
	li sp, 0x2274d58
	bne sp, a2, fail
	li sp, 0x21b496f
	bne sp, a3, fail
	li sp, 0x4df4f30f
	bne sp, a4, fail
	li sp, 0x16f23e1a
	bne sp, a5, fail
	li sp, 0x513337c8
	bne sp, a6, fail
	li sp, 0xffffffff9e7d6f79
	bne sp, a7, fail

	#==================================================================================================
	# Test Case 23 (instruction_rv32v_gen1.rb:107)

	la t1, end
	addi t1, t1, 64
	lw a0, 0(t1)
	lw a1, 4(t1)
	lw a2, 8(t1)
	lw a3, 12(t1)
	lw a4, 16(t1)
	lw a5, 20(t1)
	lw a6, 24(t1)
	lw a7, 28(t1)

	#==================================================================================================
	# Self-Checks for Test Case 23

	li sp, 0x800220c0
	bne sp, t1, fail
	ori sp, zero, 981
	bne sp, a0, fail
	li sp, 0xffffffffffffffc2
	bne sp, a1, fail
	ori sp, zero, 2
	bne sp, a2, fail
	ori sp, zero, 20
	bne sp, a3, fail
	li sp, 0xffffffffb7239466
	bne sp, a4, fail
	li sp, 0x70f060d8
	bne sp, a5, fail
	li sp, 0xffffffff9f205f8c
	bne sp, a6, fail
	li sp, 0xffffffffe0fa8dec
	bne sp, a7, fail

	#==================================================================================================
	# Test Case 24 (instruction_rv32v_gen1.rb:107)

	la t1, end
	addi t1, t1, 96
	lw a0, 0(t1)
	lw a1, 4(t1)
	lw a2, 8(t1)
	lw a3, 12(t1)
	lw a4, 16(t1)
	lw a5, 20(t1)
	lw a6, 24(t1)
	lw a7, 28(t1)

	#==================================================================================================
	# Self-Checks for Test Case 24

	li sp, 0x800220e0
	bne sp, t1, fail
	li sp, 0x153800e4
	bne sp, a0, fail
	li sp, 0x1f820a88
	bne sp, a1, fail
	li sp, 0xffffffffc3ebc1d0
	bne sp, a2, fail
	li sp, 0x39d18e14
	bne sp, a3, fail
	li sp, 0xffffffffb20b10c6
	bne sp, a4, fail
	li sp, 0xffffffffe90dc1a8
	bne sp, a5, fail
	li sp, 0xffffffffaeccc83a
	bne sp, a6, fail
	li sp, 0x6182909b
	bne sp, a7, fail

	#==================================================================================================
	# Test Case 25 (instruction_rv32v_gen1.rb:75)

	la t1, data
	vlw.v v0, (t1)
	addi t1, t1, 16
	vlw.v v4, (t1)
	addi t1, t1, 16
	vlw.v v8, (t1)
	addi t1, t1, 16
	vlw.v v12, (t1)
	addi t1, t1, 16
	vlw.v v16, (t1)
	addi t1, t1, 16
	vlw.v v20, (t1)
	addi t1, t1, 16
	vlw.v v24, (t1)
	addi t1, t1, 16
	vlw.v v28, (t1)
	addi t1, t1, 16
	vsub.vv v16, v28, v4
	vmul.vv v12, v4, v20
	vmulh.vv v8, v28, v24
	vdiv.vv v20, v0, v12
	vmulh.vv v28, v8, v8
	vmulh.vv v28, v16, v12
	vsub.vv v16, v4, v12
	vsub.vv v8, v24, v0
	vsub.vv v28, v16, v0
	vdiv.vv v24, v24, v20
	la t1, end
	vsw.v v0, (t1)
	addi t1, t1, 16
	vsw.v v4, (t1)
	addi t1, t1, 16
	vsw.v v8, (t1)
	addi t1, t1, 16
	vsw.v v12, (t1)
	addi t1, t1, 16
	vsw.v v16, (t1)
	addi t1, t1, 16
	vsw.v v20, (t1)
	addi t1, t1, 16
	vsw.v v24, (t1)
	addi t1, t1, 16
	vsw.v v28, (t1)
	addi t1, t1, 16
	nop

	#==================================================================================================
	# Self-Checks for Test Case 25

	li sp, 0x80022100
	bne sp, t1, fail

	#==================================================================================================
	# Test Case 26 (instruction_rv32v_gen1.rb:107)

	la t1, end
	addi t1, t1, 0
	lw a0, 0(t1)
	lw a1, 4(t1)
	lw a2, 8(t1)
	lw a3, 12(t1)
	lw a4, 16(t1)
	lw a5, 20(t1)
	lw a6, 24(t1)
	lw a7, 28(t1)

	#==================================================================================================
	# Self-Checks for Test Case 26

	li sp, 0x80022080
	bne sp, t1, fail
	li sp, 0x58dc02e
	bne sp, a0, fail
	li sp, 0xffffffff99e76af6
	bne sp, a1, fail
	li sp, 0xfffffffff044c4aa
	bne sp, a2, fail
	li sp, 0x46bf6b91
	bne sp, a3, fail
	li sp, 0xffffffffc15e938f
	bne sp, a4, fail
	li sp, 0x5273f522
	bne sp, a5, fail
	li sp, 0xffffffffb95ebbb0
	bne sp, a6, fail
	li sp, 0xffffffffb6e921bf
	bne sp, a7, fail

	#==================================================================================================
	# Test Case 27 (instruction_rv32v_gen1.rb:107)

	la t1, end
	addi t1, t1, 32
	lw a0, 0(t1)
	lw a1, 4(t1)
	lw a2, 8(t1)
	lw a3, 12(t1)
	lw a4, 16(t1)
	lw a5, 20(t1)
	lw a6, 24(t1)
	lw a7, 28(t1)

	#==================================================================================================
	# Self-Checks for Test Case 27

	li sp, 0x800220a0
	bne sp, t1, fail
	li sp, 0xffffffffb8fbac89
	bne sp, a0, fail
	li sp, 0xffffffffbe534d0a
	bne sp, a1, fail
	li sp, 0x7032f52
	bne sp, a2, fail
	li sp, 0x78293576
	bne sp, a3, fail
	li sp, 0x2695498b
	bne sp, a4, fail
	li sp, 0xffffffffa8bfd388
	bne sp, a5, fail
	li sp, 0x40fff1a0
	bne sp, a6, fail
	li sp, 0xffffffff8d330bd4
	bne sp, a7, fail

	#==================================================================================================
	# Test Case 28 (instruction_rv32v_gen1.rb:107)

	la t1, end
	addi t1, t1, 64
	lw a0, 0(t1)
	lw a1, 4(t1)
	lw a2, 8(t1)
	lw a3, 12(t1)
	lw a4, 16(t1)
	lw a5, 20(t1)
	lw a6, 24(t1)
	lw a7, 28(t1)

	#==================================================================================================
	# Self-Checks for Test Case 28

	li sp, 0x800220c0
	bne sp, t1, fail
	li sp, 0xffffffff9ac94a04
	bne sp, a0, fail
	li sp, 0xffffffffa9b4219a
	bne sp, a1, fail
	li sp, 0x785eca10
	bne sp, a2, fail
	li sp, 0x29b615eb
	bne sp, a3, fail
	bne zero, a4, fail
	ori sp, zero, 1
	bne sp, a5, fail
	bne zero, a6, fail
	bne zero, a7, fail

	#==================================================================================================
	# Test Case 29 (instruction_rv32v_gen1.rb:107)

	la t1, end
	addi t1, t1, 96
	lw a0, 0(t1)
	lw a1, 4(t1)
	lw a2, 8(t1)
	lw a3, 12(t1)
	lw a4, 16(t1)
	lw a5, 20(t1)
	lw a6, 24(t1)
	lw a7, 28(t1)

	#==================================================================================================
	# Self-Checks for Test Case 29

	li sp, 0x800220e0
	bne sp, t1, fail
	not sp, zero
	bne sp, a0, fail
	li sp, 0x583ab800
	bne sp, a1, fail
	not sp, zero
	bne sp, a2, fail
	not sp, zero
	bne sp, a3, fail
	li sp, 0xffffffff953b89d6
	bne sp, a4, fail
	li sp, 0xfccb6a4
	bne sp, a5, fail
	li sp, 0xffffffff881a0566
	bne sp, a6, fail
	li sp, 0xffffffffe2f6aa5a
	bne sp, a7, fail

	#==================================================================================================
	# Test Case 30 (instruction_rv32v_gen1.rb:75)

	la t1, data
	vlw.v v0, (t1)
	addi t1, t1, 16
	vlw.v v4, (t1)
	addi t1, t1, 16
	vlw.v v8, (t1)
	addi t1, t1, 16
	vlw.v v12, (t1)
	addi t1, t1, 16
	vlw.v v16, (t1)
	addi t1, t1, 16
	vlw.v v20, (t1)
	addi t1, t1, 16
	vlw.v v24, (t1)
	addi t1, t1, 16
	vlw.v v28, (t1)
	addi t1, t1, 16
	vdiv.vv v16, v8, v4
	vsub.vv v4, v0, v8
	vmulh.vv v4, v4, v8
	vdiv.vv v24, v28, v8
	vmulh.vv v16, v8, v8
	vmulh.vv v0, v16, v20
	vsub.vv v20, v4, v8
	vdiv.vv v16, v12, v28
	vadd.vv v0, v12, v16
	vsub.vv v4, v4, v16
	la t1, end
	vsw.v v0, (t1)
	addi t1, t1, 16
	vsw.v v4, (t1)
	addi t1, t1, 16
	vsw.v v8, (t1)
	addi t1, t1, 16
	vsw.v v12, (t1)
	addi t1, t1, 16
	vsw.v v16, (t1)
	addi t1, t1, 16
	vsw.v v20, (t1)
	addi t1, t1, 16
	vsw.v v24, (t1)
	addi t1, t1, 16
	vsw.v v28, (t1)
	addi t1, t1, 16
	nop

	#==================================================================================================
	# Self-Checks for Test Case 30

	li sp, 0x80022100
	bne sp, t1, fail

	#==================================================================================================
	# Test Case 31 (instruction_rv32v_gen1.rb:107)

	la t1, end
	addi t1, t1, 0
	lw a0, 0(t1)
	lw a1, 4(t1)
	lw a2, 8(t1)
	lw a3, 12(t1)
	lw a4, 16(t1)
	lw a5, 20(t1)
	lw a6, 24(t1)
	lw a7, 28(t1)

	#==================================================================================================
	# Self-Checks for Test Case 31

	li sp, 0x80022080
	bne sp, t1, fail
	li sp, 0x6884a2f9
	bne sp, a0, fail
	li sp, 0x523b2450
	bne sp, a1, fail
	li sp, 0x7d9d2f06
	bne sp, a2, fail
	li sp, 0x62210d5b
	bne sp, a3, fail
	li sp, 0xfffffffffda30c4c
	bne sp, a4, fail
	li sp, 0x11e358db
	bne sp, a5, fail
	li sp, 0xffffffffe5db11e2
	bne sp, a6, fail
	li sp, 0xfffffffffac76e01
	bne sp, a7, fail

	#==================================================================================================
	# Test Case 32 (instruction_rv32v_gen1.rb:107)

	la t1, end
	addi t1, t1, 32
	lw a0, 0(t1)
	lw a1, 4(t1)
	lw a2, 8(t1)
	lw a3, 12(t1)
	lw a4, 16(t1)
	lw a5, 20(t1)
	lw a6, 24(t1)
	lw a7, 28(t1)

	#==================================================================================================
	# Self-Checks for Test Case 32

	li sp, 0x800220a0
	bne sp, t1, fail
	li sp, 0xffffffffea065b28
	bne sp, a0, fail
	li sp, 0x2850aa8b
	bne sp, a1, fail
	li sp, 0xffffffffa5f25cbd
	bne sp, a2, fail
	li sp, 0x563ebde5
	bne sp, a3, fail
	li sp, 0x6884a2fa
	bne sp, a4, fail
	li sp, 0x523b2453
	bne sp, a5, fail
	li sp, 0x7d9d2f07
	bne sp, a6, fail
	li sp, 0x62210d5a
	bne sp, a7, fail

	#==================================================================================================
	# Test Case 33 (instruction_rv32v_gen1.rb:107)

	la t1, end
	addi t1, t1, 64
	lw a0, 0(t1)
	lw a1, 4(t1)
	lw a2, 8(t1)
	lw a3, 12(t1)
	lw a4, 16(t1)
	lw a5, 20(t1)
	lw a6, 24(t1)
	lw a7, 28(t1)

	#==================================================================================================
	# Self-Checks for Test Case 33

	li sp, 0x800220c0
	bne sp, t1, fail
	not sp, zero
	bne sp, a0, fail
	li sp, 0xfffffffffffffffd
	bne sp, a1, fail
	not sp, zero
	bne sp, a2, fail
	ori sp, zero, 1
	bne sp, a3, fail
	li sp, 0x139cb123
	bne sp, a4, fail
	li sp, 0xffffffffe992ae4d
	bne sp, a5, fail
	li sp, 0x3fe8b524
	bne sp, a6, fail
	li sp, 0xffffffffa488b01d
	bne sp, a7, fail

	#==================================================================================================
	# Test Case 34 (instruction_rv32v_gen1.rb:107)

	la t1, end
	addi t1, t1, 96
	lw a0, 0(t1)
	lw a1, 4(t1)
	lw a2, 8(t1)
	lw a3, 12(t1)
	lw a4, 16(t1)
	lw a5, 20(t1)
	lw a6, 24(t1)
	lw a7, 28(t1)

	#==================================================================================================
	# Self-Checks for Test Case 34

	li sp, 0x800220e0
	bne sp, t1, fail
	ori sp, zero, 3
	bne sp, a0, fail
	bne zero, a1, fail
	bne zero, a2, fail
	ori sp, zero, 1
	bne sp, a3, fail
	li sp, 0xffffffffb20b10c6
	bne sp, a4, fail
	li sp, 0xffffffffe90dc1a8
	bne sp, a5, fail
	li sp, 0xffffffffaeccc83a
	bne sp, a6, fail
	li sp, 0x6182909b
	bne sp, a7, fail

	#==================================================================================================
	# Test Case 35 (instruction_rv32v_gen1.rb:75)

	la t1, data
	vlw.v v0, (t1)
	addi t1, t1, 16
	vlw.v v4, (t1)
	addi t1, t1, 16
	vlw.v v8, (t1)
	addi t1, t1, 16
	vlw.v v12, (t1)
	addi t1, t1, 16
	vlw.v v16, (t1)
	addi t1, t1, 16
	vlw.v v20, (t1)
	addi t1, t1, 16
	vlw.v v24, (t1)
	addi t1, t1, 16
	vlw.v v28, (t1)
	addi t1, t1, 16
	vadd.vv v0, v24, v8
	vmul.vv v8, v24, v8
	vadd.vv v12, v4, v12
	vmul.vv v0, v4, v24
	vmulh.vv v16, v12, v20
	vmul.vv v12, v8, v0
	vmul.vv v28, v4, v0
	vadd.vv v16, v12, v24
	vsub.vv v4, v24, v20
	vmul.vv v0, v12, v24
	la t1, end
	vsw.v v0, (t1)
	addi t1, t1, 16
	vsw.v v4, (t1)
	addi t1, t1, 16
	vsw.v v8, (t1)
	addi t1, t1, 16
	vsw.v v12, (t1)
	addi t1, t1, 16
	vsw.v v16, (t1)
	addi t1, t1, 16
	vsw.v v20, (t1)
	addi t1, t1, 16
	vsw.v v24, (t1)
	addi t1, t1, 16
	vsw.v v28, (t1)
	addi t1, t1, 16
	nop

	#==================================================================================================
	# Self-Checks for Test Case 35

	li sp, 0x80022100
	bne sp, t1, fail

	#==================================================================================================
	# Test Case 36 (instruction_rv32v_gen1.rb:107)

	la t1, end
	addi t1, t1, 0
	lw a0, 0(t1)
	lw a1, 4(t1)
	lw a2, 8(t1)
	lw a3, 12(t1)
	lw a4, 16(t1)
	lw a5, 20(t1)
	lw a6, 24(t1)
	lw a7, 28(t1)

	#==================================================================================================
	# Self-Checks for Test Case 36

	li sp, 0x80022080
	bne sp, t1, fail
	li sp, 0xffffffffaa36e068
	bne sp, a0, fail
	bne zero, a1, fail
	li sp, 0xcefc400
	bne sp, a2, fail
	li sp, 0xffffffff92a0846d
	bne sp, a3, fail
	li sp, 0xffffffffdd2b3072
	bne sp, a4, fail
	li sp, 0x50c5f07c
	bne sp, a5, fail
	li sp, 0x4dfe014e
	bne sp, a6, fail
	li sp, 0xffffffffda081fdb
	bne sp, a7, fail

	#==================================================================================================
	# Test Case 37 (instruction_rv32v_gen1.rb:107)

	la t1, end
	addi t1, t1, 32
	lw a0, 0(t1)
	lw a1, 4(t1)
	lw a2, 8(t1)
	lw a3, 12(t1)
	lw a4, 16(t1)
	lw a5, 20(t1)
	lw a6, 24(t1)
	lw a7, 28(t1)

	#==================================================================================================
	# Self-Checks for Test Case 37

	li sp, 0x800220a0
	bne sp, t1, fail
	li sp, 0x71680998
	bne sp, a0, fail
	li sp, 0x6611e800
	bne sp, a1, fail
	li sp, 0x7c05b10c
	bne sp, a2, fail
	li sp, 0xffffffffdeac3643
	bne sp, a3, fail
	li sp, 0x7c1c0ad8
	bne sp, a4, fail
	li sp, 0x75800000
	bne sp, a5, fail
	li sp, 0xffffffff85970f00
	bne sp, a6, fail
	li sp, 0xffffffff9dfff5eb
	bne sp, a7, fail

	#==================================================================================================
	# Test Case 38 (instruction_rv32v_gen1.rb:107)

	la t1, end
	addi t1, t1, 64
	lw a0, 0(t1)
	lw a1, 4(t1)
	lw a2, 8(t1)
	lw a3, 12(t1)
	lw a4, 16(t1)
	lw a5, 20(t1)
	lw a6, 24(t1)
	lw a7, 28(t1)

	#==================================================================================================
	# Self-Checks for Test Case 38

	li sp, 0x800220c0
	bne sp, t1, fail
	li sp, 0x3aa5778f
	bne sp, a0, fail
	li sp, 0xffffffffcdbab800
	bne sp, a1, fail
	li sp, 0x7cdf02fc
	bne sp, a2, fail
	li sp, 0x5ce896f2
	bne sp, a3, fail
	li sp, 0xffffffffe15e3c45
	bne sp, a4, fail
	li sp, 0x774c784
	bne sp, a5, fail
	li sp, 0xffffffffa949f2ae
	bne sp, a6, fail
	li sp, 0xffffffffe4e0812c
	bne sp, a7, fail

	#==================================================================================================
	# Test Case 39 (instruction_rv32v_gen1.rb:107)

	la t1, end
	addi t1, t1, 96
	lw a0, 0(t1)
	lw a1, 4(t1)
	lw a2, 8(t1)
	lw a3, 12(t1)
	lw a4, 16(t1)
	lw a5, 20(t1)
	lw a6, 24(t1)
	lw a7, 28(t1)

	#==================================================================================================
	# Self-Checks for Test Case 39

	li sp, 0x800220e0
	bne sp, t1, fail
	li sp, 0xffffffffbe896cb7
	bne sp, a0, fail
	li sp, 0x583ab800
	bne sp, a1, fail
	li sp, 0xfffffffff747f3fc
	bne sp, a2, fail
	li sp, 0xffffffffbee8a107
	bne sp, a3, fail
	li sp, 0x6a1d7bd7
	bne sp, a4, fail
	li sp, 0x4f86e000
	bne sp, a5, fail
	li sp, 0xffffffffcd699c00
	bne sp, a6, fail
	li sp, 0xffffffffde6ab887
	bne sp, a7, fail

	#==================================================================================================
	# Test Case 40 (instruction_rv32v_gen1.rb:75)

	la t1, data
	vlw.v v0, (t1)
	addi t1, t1, 16
	vlw.v v4, (t1)
	addi t1, t1, 16
	vlw.v v8, (t1)
	addi t1, t1, 16
	vlw.v v12, (t1)
	addi t1, t1, 16
	vlw.v v16, (t1)
	addi t1, t1, 16
	vlw.v v20, (t1)
	addi t1, t1, 16
	vlw.v v24, (t1)
	addi t1, t1, 16
	vlw.v v28, (t1)
	addi t1, t1, 16
	vsub.vv v4, v24, v4
	vadd.vv v4, v28, v4
	vsub.vv v24, v20, v0
	vadd.vv v4, v12, v8
	vsub.vv v0, v8, v8
	vdiv.vv v24, v28, v0
	vmul.vv v16, v8, v4
	vmul.vv v20, v4, v28
	vsub.vv v24, v24, v28
	vadd.vv v28, v28, v28
	la t1, end
	vsw.v v0, (t1)
	addi t1, t1, 16
	vsw.v v4, (t1)
	addi t1, t1, 16
	vsw.v v8, (t1)
	addi t1, t1, 16
	vsw.v v12, (t1)
	addi t1, t1, 16
	vsw.v v16, (t1)
	addi t1, t1, 16
	vsw.v v20, (t1)
	addi t1, t1, 16
	vsw.v v24, (t1)
	addi t1, t1, 16
	vsw.v v28, (t1)
	addi t1, t1, 16
	nop

	#==================================================================================================
	# Self-Checks for Test Case 40

	li sp, 0x80022100
	bne sp, t1, fail

	#==================================================================================================
	# Test Case 41 (instruction_rv32v_gen1.rb:107)

	la t1, end
	addi t1, t1, 0
	lw a0, 0(t1)
	lw a1, 4(t1)
	lw a2, 8(t1)
	lw a3, 12(t1)
	lw a4, 16(t1)
	lw a5, 20(t1)
	lw a6, 24(t1)
	lw a7, 28(t1)

	#==================================================================================================
	# Self-Checks for Test Case 41

	li sp, 0x80022080
	bne sp, t1, fail
	bne zero, a0, fail
	bne zero, a1, fail
	bne zero, a2, fail
	bne zero, a3, fail
	li sp, 0x528afe22
	bne sp, a4, fail
	li sp, 0x7a8bcede
	bne sp, a5, fail
	li sp, 0x238f8bc4
	bne sp, a6, fail
	li sp, 0xffffffffb85fcb3f
	bne sp, a7, fail

	#==================================================================================================
	# Test Case 42 (instruction_rv32v_gen1.rb:107)

	la t1, end
	addi t1, t1, 32
	lw a0, 0(t1)
	lw a1, 4(t1)
	lw a2, 8(t1)
	lw a3, 12(t1)
	lw a4, 16(t1)
	lw a5, 20(t1)
	lw a6, 24(t1)
	lw a7, 28(t1)

	#==================================================================================================
	# Self-Checks for Test Case 42

	li sp, 0x800220a0
	bne sp, t1, fail
	li sp, 0xffffffffea065b28
	bne sp, a0, fail
	li sp, 0x2850aa8b
	bne sp, a1, fail
	li sp, 0xffffffffa5f25cbd
	bne sp, a2, fail
	li sp, 0x563ebde5
	bne sp, a3, fail
	li sp, 0x6884a2fa
	bne sp, a4, fail
	li sp, 0x523b2453
	bne sp, a5, fail
	li sp, 0x7d9d2f07
	bne sp, a6, fail
	li sp, 0x62210d5a
	bne sp, a7, fail

	#==================================================================================================
	# Test Case 43 (instruction_rv32v_gen1.rb:107)

	la t1, end
	addi t1, t1, 64
	lw a0, 0(t1)
	lw a1, 4(t1)
	lw a2, 8(t1)
	lw a3, 12(t1)
	lw a4, 16(t1)
	lw a5, 20(t1)
	lw a6, 24(t1)
	lw a7, 28(t1)

	#==================================================================================================
	# Self-Checks for Test Case 43

	li sp, 0x800220c0
	bne sp, t1, fail
	li sp, 0x56d9cb50
	bne sp, a0, fail
	li sp, 0xffffffffb6a8be8a
	bne sp, a1, fail
	li sp, 0x4a7c9fb4
	bne sp, a2, fail
	li sp, 0xa00525b
	bne sp, a3, fail
	li sp, 0x16d8ae4c
	bne sp, a4, fail
	li sp, 0x61fb1fb0
	bne sp, a5, fail
	li sp, 0xffffffffcbe6ca68
	bne sp, a6, fail
	li sp, 0xffffffff99517f25
	bne sp, a7, fail

	#==================================================================================================
	# Test Case 44 (instruction_rv32v_gen1.rb:107)

	la t1, end
	addi t1, t1, 96
	lw a0, 0(t1)
	lw a1, 4(t1)
	lw a2, 8(t1)
	lw a3, 12(t1)
	lw a4, 16(t1)
	lw a5, 20(t1)
	lw a6, 24(t1)
	lw a7, 28(t1)

	#==================================================================================================
	# Self-Checks for Test Case 44

	li sp, 0x800220e0
	bne sp, t1, fail
	li sp, 0x4df4ef39
	bne sp, a0, fail
	li sp, 0x16f23e57
	bne sp, a1, fail
	li sp, 0x513337c5
	bne sp, a2, fail
	li sp, 0xffffffff9e7d6f64
	bne sp, a3, fail
	li sp, 0x6416218c
	bne sp, a4, fail
	li sp, 0xffffffffd21b8350
	bne sp, a5, fail
	li sp, 0x5d999074
	bne sp, a6, fail
	li sp, 0xffffffffc3052136
	bne sp, a7, fail

	#==================================================================================================
	# Test Case 45 (instruction_rv32v_gen1.rb:75)

	la t1, data
	vlw.v v0, (t1)
	addi t1, t1, 16
	vlw.v v4, (t1)
	addi t1, t1, 16
	vlw.v v8, (t1)
	addi t1, t1, 16
	vlw.v v12, (t1)
	addi t1, t1, 16
	vlw.v v16, (t1)
	addi t1, t1, 16
	vlw.v v20, (t1)
	addi t1, t1, 16
	vlw.v v24, (t1)
	addi t1, t1, 16
	vlw.v v28, (t1)
	addi t1, t1, 16
	vmulh.vv v24, v4, v8
	vsub.vv v12, v24, v24
	vadd.vv v16, v8, v28
	vmul.vv v28, v16, v24
	vsub.vv v12, v12, v12
	vmulh.vv v0, v24, v12
	vmulh.vv v20, v16, v4
	vmulh.vv v20, v12, v4
	vmulh.vv v12, v24, v8
	vmulh.vv v24, v24, v24
	la t1, end
	vsw.v v0, (t1)
	addi t1, t1, 16
	vsw.v v4, (t1)
	addi t1, t1, 16
	vsw.v v8, (t1)
	addi t1, t1, 16
	vsw.v v12, (t1)
	addi t1, t1, 16
	vsw.v v16, (t1)
	addi t1, t1, 16
	vsw.v v20, (t1)
	addi t1, t1, 16
	vsw.v v24, (t1)
	addi t1, t1, 16
	vsw.v v28, (t1)
	addi t1, t1, 16
	nop

	#==================================================================================================
	# Self-Checks for Test Case 45

	li sp, 0x80022100
	bne sp, t1, fail

	#==================================================================================================
	# Test Case 46 (instruction_rv32v_gen1.rb:107)

	la t1, end
	addi t1, t1, 0
	lw a0, 0(t1)
	lw a1, 4(t1)
	lw a2, 8(t1)
	lw a3, 12(t1)
	lw a4, 16(t1)
	lw a5, 20(t1)
	lw a6, 24(t1)
	lw a7, 28(t1)

	#==================================================================================================
	# Self-Checks for Test Case 46

	li sp, 0x80022080
	bne sp, t1, fail
	bne zero, a0, fail
	bne zero, a1, fail
	bne zero, a2, fail
	bne zero, a3, fail
	li sp, 0xffffffffc15e938f
	bne sp, a4, fail
	li sp, 0x5273f522
	bne sp, a5, fail
	li sp, 0xffffffffb95ebbb0
	bne sp, a6, fail
	li sp, 0xffffffffb6e921bf
	bne sp, a7, fail

	#==================================================================================================
	# Test Case 47 (instruction_rv32v_gen1.rb:107)

	la t1, end
	addi t1, t1, 32
	lw a0, 0(t1)
	lw a1, 4(t1)
	lw a2, 8(t1)
	lw a3, 12(t1)
	lw a4, 16(t1)
	lw a5, 20(t1)
	lw a6, 24(t1)
	lw a7, 28(t1)

	#==================================================================================================
	# Self-Checks for Test Case 47

	li sp, 0x800220a0
	bne sp, t1, fail
	li sp, 0xffffffffea065b28
	bne sp, a0, fail
	li sp, 0x2850aa8b
	bne sp, a1, fail
	li sp, 0xffffffffa5f25cbd
	bne sp, a2, fail
	li sp, 0x563ebde5
	bne sp, a3, fail
	li sp, 0xffffffffff89db30
	bne sp, a4, fail
	li sp, 0x20b7b69
	bne sp, a5, fail
	li sp, 0xfffffffff74293f1
	bne sp, a6, fail
	li sp, 0xfffffffff7b459e1
	bne sp, a7, fail

	#==================================================================================================
	# Test Case 48 (instruction_rv32v_gen1.rb:107)

	la t1, end
	addi t1, t1, 64
	lw a0, 0(t1)
	lw a1, 4(t1)
	lw a2, 8(t1)
	lw a3, 12(t1)
	lw a4, 16(t1)
	lw a5, 20(t1)
	lw a6, 24(t1)
	lw a7, 28(t1)

	#==================================================================================================
	# Self-Checks for Test Case 48

	li sp, 0x800220c0
	bne sp, t1, fail
	li sp, 0xffffffff9c116bee
	bne sp, a0, fail
	li sp, 0x115e6c33
	bne sp, a1, fail
	li sp, 0x54bf24f7
	bne sp, a2, fail
	li sp, 0xffffffffb7c14e80
	bne sp, a3, fail
	bne zero, a4, fail
	bne zero, a5, fail
	bne zero, a6, fail
	bne zero, a7, fail

	#==================================================================================================
	# Test Case 49 (instruction_rv32v_gen1.rb:107)

	la t1, end
	addi t1, t1, 96
	lw a0, 0(t1)
	lw a1, 4(t1)
	lw a2, 8(t1)
	lw a3, 12(t1)
	lw a4, 16(t1)
	lw a5, 20(t1)
	lw a6, 24(t1)
	lw a7, 28(t1)

	#==================================================================================================
	# Self-Checks for Test Case 49

	li sp, 0x800220e0
	bne sp, t1, fail
	li sp, 0x1ce769
	bne sp, a0, fail
	li sp, 0xa89aa5
	bne sp, a1, fail
	li sp, 0x2694d01
	bne sp, a2, fail
	li sp, 0x25e5012
	bne sp, a3, fail
	li sp, 0x367b99c8
	bne sp, a4, fail
	li sp, 0x31a946b5
	bne sp, a5, fail
	li sp, 0xffffffff8f56fbc9
	bne sp, a6, fail
	li sp, 0xffffffffaa183080
	bne sp, a7, fail

	#==================================================================================================
	# Epilogue (riscv_base.rb:290)

	j pass
fail:
	fence
1:
	beqz gp, 1b
	sll gp, gp, ra
	or gp, gp, ra
	ecall
pass:
	fence
	li gp, 0x1
	ecall
	unimp

	#==================================================================================================
	# Data

	#============================================= .data ==============================================
	.data

	#========================================== Global Data ===========================================
	.align 4
	.pushsection .tohost,"aw",@progbits
	.align 8; .global tohost; tohost: .dword 0;
	.align 8; .global fromhost; fromhost: .dword 0;
	.popsection;
	.align 4
	.globl begin_signature
begin_signature:

data:
	.word 0x58DC02E, 0x99E76AF6
	.word 0xF044C4AA, 0x46BF6B91
	.word 0xC15E938F, 0x5273F522
	.word 0xB95EBBB0, 0xB6E921BF
	.word 0xEA065B28, 0x2850AA8B
	.word 0xA5F25CBD, 0x563EBDE5
	.word 0x6884A2FA, 0x523B2453
	.word 0x7D9D2F07, 0x62210D5A
	.word 0xDAC7E70, 0xF29BC9A9
	.word 0x3DFDE178, 0x1C229DE6
	.word 0xE15E3C45, 0x774C784
	.word 0xA949F2AE, 0xE4E0812C
	.word 0xBE896CB7, 0x583AB800
	.word 0xF747F3FC, 0xBEE8A107
	.word 0xB20B10C6, 0xE90DC1A8
	.word 0xAECCC83A, 0x6182909B
end:
	.skip 1

	.align 4
	.globl end_signature
end_signature:
	.align 8; .global begin_regstate; begin_regstate:
	.word 128;
	.align 8; .global end_regstate; end_regstate:
	.word 4;
